<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sun, 03 Apr 2016 19:30:11 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Forumo pranešimas';
$l['announcements'] = 'Pranešimas';
$l['forum_announcement'] = 'Forumo pranešimas: {1}';
$l['error_invalidannouncement'] = 'Nurodytas pranešimas yra neteisingas.';
$l['announcement_edit'] = 'Redaguoti šį pranešimą';
$l['announcement_qdelete'] = 'Ištrinti šį pranešimą';
$l['announcement_quickdelete_confirm'] = 'Ar tikrai norite ištrinti šį pranešimą?';
