<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sun, 03 Apr 2016 19:34:15 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Pilna versija:';
$l['archive_replies'] = 'Atsakymai';
$l['archive_reply'] = 'Atsakyti';
$l['archive_pages'] = 'Puslapiai:';
$l['archive_note'] = 'You\'re currently viewing a stripped down version of our content. <a href="{1}">View the full version</a> with proper formatting.';
$l['archive_nopermission'] = 'Atsiprašome, bet jūs neturite leidimo prieiti prie šių duomenų.';
$l['error_nothreads'] = 'Šiuo metu nėra jokių šio forumo temų.';
$l['error_nopermission'] = 'Jūs neturite leidimo peržiūrėti temas šiame forume.';
$l['error_unapproved_thread'] = 'Ši tema yra nepatvirtinta. Prašome <a href="{1}">peržiūrėti pilną šio pokalbio versiją</a>.';
$l['archive_not_found'] = 'Ieškomas puslapis nerastas šiame serveryje.';
$l['error_mustlogin'] = 'Ši skelbimų lenta reikalauja visus vartotojus prisijungti.';
