<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Tue, 17 May 2016 06:24:31 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Susisiekite su mumis';
$l['contact_no_message'] = 'Jūs nenurodėte žinutės išsiuntimui.';
$l['contact_no_subject'] = 'Jūs privalote įvesti pavadinimą.';
$l['contact_no_email'] = 'Jūs privalote įvesti teisingą el. pašto adresą.';
$l['contact_success_message'] = 'Jūsų žinutė sėkmingai išsiųsta administratoriui.';
$l['contact_subject'] = 'Pavadinimas';
$l['contact_subject_desc'] = 'Brief the topic of your message.';
$l['contact_message'] = 'Žinutė';
$l['contact_message_desc'] = 'Describe your concern in this area in detail.';
$l['contact_email'] = 'El. paštas';
$l['contact_email_desc'] = 'Enter your email so we can contact you back.';
$l['contact_send'] = 'Siųsti';
$l['subject_too_long'] = 'The subject is too long. Please enter a subject shorter than {1} characters (currently {2}).';
$l['message_too_short'] = 'The message is too short. Please enter a message longer than {1} characters (currently {2}).';
$l['message_too_long'] = 'The message is too long. Please enter a message shorter than {1} characters (currently {2}).';
$l['error_stop_forum_spam_spammer'] = 'Sorry, {1} matches that of a known spammer and therefore your contact submission has been blocked.';
$l['error_stop_forum_spam_fetching'] = 'Sorry, something went wrong verifying your message against a spammer database. Most likely the database couldn\'t be accessed. Please try again later.';
