<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Mon, 25 Jul 2016 13:05:08 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = 'Redaguoti pranešimą';
$l['edit_post'] = 'Redaguoti šį pranešimą';
$l['delete_post'] = 'Ištrinti pranešimą';
$l['delete_q'] = 'Ištrinti?';
$l['delete_1'] = 'Kad ištrintumėte šį pranešimą, pažymėkite jį varnele kairėje pusėje ir tada spauskite mygtuką dešinėje.';
$l['delete_2'] = '<b>Pastaba:</b> Jeigu šis pranešimas yra pirmas temoje, bus ištrinta visa tema.';
$l['subject'] = 'Temos eilutė';
$l['your_message'] = 'Tavo tekstats';
$l['post_options'] = 'Pranešimo nustatymai:';
$l['editreason'] = 'Redagavimo priežastis:';
$l['options_sig'] = '<strong>Parašas:</strong> įterpti parašą. (tik registruoti)';
$l['options_emailnotify'] = '<strong>El. Pašto pranešimai:</strong> gausite laišką, kai yra naujas atsakymas. (tik registruoti)';
$l['options_disablesmilies'] = '<strong>Išjungti šypsenėles:</strong> nerodyti šyspenėlių šiame pranešime.';
$l['preview_post'] = 'Peržiūrėti pranešimą';
$l['update_post'] = 'Atnaujinti pranešimą';
$l['poll'] = 'Apklausa:';
$l['poll_desc'] = 'Pasirinktinai galite pridėti apklausą šioje temoje.';
$l['poll_check'] = 'Noriu pateikti apklausą';
$l['num_options'] = 'Pasirinkimų skaičius:';
$l['max_options'] = '(Daugiausiai: {1})';
$l['delete_now'] = 'Ištrinti dabar';
$l['edit_time_limit'] = 'Atsiprašome, bet jūs negalite redaguoti savo pranešimo. Administratorius nustatė taip, kad pranešimai gali būti redaguoti tik per {1} minutes po publikavimo.';
$l['no_prefix'] = 'Nėra priešdėlio';
$l['redirect_nodelete'] = 'Pranešimas nebuvo ištrintas, nes nepasirinktas \'Ištrinti\' laukelis.';
$l['redirect_norestore'] = 'Pranešimas nebuvo atstatytas, nes nepasirinktas \'Atstatyti\' laukelis.';
$l['redirect_postedited'] = 'Dėkojame, šis pranešimas buvo redaguotas.<br />';
$l['redirect_postedited_redirect'] = 'Jūs dabar bus grąžintas į pokalbį.';
$l['redirect_postedited_poll'] = 'Dėkojame, šis pranešimas buvo redaguotas. <br />Kadangi jūs pasirinkote kurti apklausą, dabar būsite nukreiptas į apklausos kūrimo puslapį.';
$l['error_invalidpost'] = 'Sorry, but you seem to have followed an invalid address. Please be sure the specified post exists and try again.';
$l['redirect_threaddeleted'] = 'Dėkojame, tema buvo ištrinta.<br />Dabar Jūs būsite nukreiptas į forumą.';
$l['redirect_postdeleted'] = 'Dėkojame, pranešimas buvo ištrintas.<br />Dabar Jūs būsite nukreiptas į temą.';
$l['redirect_threadrestored'] = 'Dėkojame, Jūsų tema atstatyta.<br />Dabar Jūs būsite nukreiptas į forumą.';
$l['redirect_postrestored'] = 'Dėkojame, pranešimas atstaytas.<br />Dabar Jūs būsite nukreiptas į temą.';
$l['redirect_threadclosed'] = 'Jūs negalite redaguoti esamus pranešimus šioje temoje, nes ji buvo uždaryta moderatoriaus.';
$l['redirect_post_moderation'] = 'Administratorius nurodė, kad visų žinučių redagavimas reikalauja moderavimo. Dabar Jūs būsite nukreiptas į temą.';
$l['redirect_thread_moderation'] = 'Administratorius nurodė, kad visų temų redagavimas reikalauja moderavimo. Dabar Jūs būsite nukreiptas į forumo pradžią.';
$l['error_already_delete'] = 'Atsiprašome, bet šis pranešimas jau yra ištrintas.';
$l['thread_deleted'] = 'Ištrinta tema';
$l['post_deleted'] = 'Ištrintas pranešimas';
$l['thread_soft_deleted'] = 'Panaikinta tema';
$l['post_soft_deleted'] = 'Panaikintas pranešimas';
$l['thread_restored'] = 'Atkurta tema';
$l['post_restored'] = 'Atkurtas pranešimas';
$l['error_already_deleted'] = 'Pasirinktas pranešimas jau buvo ištrintas.';
