<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Tue, 17 May 2016 06:26:34 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Naujas įrašas';
$l['moderated_by'] = 'Moderuoja:';
$l['nothreads'] = 'Sorry, but there are currently no threads in this forum with the specified date and time limiting options.';
$l['nopermission'] = 'Atsiprašome, bet jūs neturite leidimo peržiūrėti temas šiame forume.';
$l['search_forum'] = 'Ieškoti šiame forume:';
$l['thread'] = 'Tema';
$l['author'] = 'Autorius';
$l['replies'] = 'Atsakymai';
$l['views'] = 'Peržiūros';
$l['lastpost'] = 'Naujausias įrašas';
$l['rating'] = 'Įvertinimas';
$l['prefix'] = 'Priešdėlis:';
$l['prefix_all'] = 'Priešdėlis: Visi/Jokio';
$l['prefix_any'] = 'Priešdėlis: Betkoks';
$l['prefix_none'] = 'Priešdėlis: Jokio';
$l['markforum_read'] = 'Pažymėti šį forumą kaip skaitytą';
$l['subscribe_forum'] = 'Prenumeruoti šį forumą';
$l['unsubscribe_forum'] = 'Atsisakyti prenumeratos šiame forume';
$l['clear_stored_password'] = 'Išvalyti saugomą forumo slaptažodis';
$l['sort_by_subject'] = 'Rūšiuoti pagal: Tema';
$l['sort_by_lastpost'] = 'Rūšiuoti pagal: Naujausias įrašas';
$l['sort_by_starter'] = 'Rūšiuoti pagal: Autorius';
$l['sort_by_started'] = 'Rūšiuoti pagal: Sukūrimo laikas';
$l['sort_by_rating'] = 'Rūšiuoti pagal: Įvertinimas';
$l['sort_by_replies'] = 'Rūšiuoti pagal: Atsakymai';
$l['sort_by_views'] = 'Rūšiuoti pagal: Peržiūras';
$l['sort_order_asc'] = 'Rūšiuoti pagal: Didėjančia tvarka';
$l['sort_order_desc'] = 'Rūšiuoti pagal: Mažėjančia tvarka';
$l['datelimit_1day'] = 'Nuo: Šiandien';
$l['datelimit_5days'] = 'Nuo: prieš 5 dienas';
$l['datelimit_10days'] = 'Nuo: prieš 10 dienų';
$l['datelimit_20days'] = 'Nuo: prieš 20 dienų';
$l['datelimit_50days'] = 'Nuo: prieš 50 dienų';
$l['datelimit_75days'] = 'Nuo: prieš 75 dienų';
$l['datelimit_100days'] = 'Nuo: prieš 100 dienų';
$l['datelimit_lastyear'] = 'Nuo: prieš 1 metus';
$l['datelimit_beginning'] = 'Nuo: prieš pradžių';
$l['new_thread'] = 'Naujos žinutės';
$l['new_hot_thread'] = 'Karšta tema (New)';
$l['posts_by_you'] = 'Tavo žinutės';
$l['no_new_thread'] = 'Nėra naujų pranešimų';
$l['hot_thread'] = 'Karšta tema (Nėra naujų)';
$l['locked_thread'] = 'Užrakinta tema';
$l['goto_first_unread'] = 'Eiti į pirmą neperskaitytą žinutę';
$l['pages'] = 'Puslapiai:';
$l['pages_last'] = 'paskutinis';
$l['users_browsing_forum'] = 'Vartotojai naršantys šį forumą:';
$l['users_browsing_forum_guests'] = '{1} Svečias(-iai)';
$l['users_browsing_forum_invis'] = '{1} Nematomi(-as) vartotojai(-ai)';
$l['delayed_moderation'] = 'Atidėtas moderavimui';
$l['inline_thread_moderation'] = 'Inline Thread Moderation:';
$l['close_threads'] = 'Uždarytos temos';
$l['open_threads'] = 'Atviros temos';
$l['stick_threads'] = 'Svarbios temos';
$l['unstick_threads'] = 'Nesvarbios temos';
$l['soft_delete_threads'] = 'Panaikinti temą';
$l['restore_threads'] = 'Atstatyti temą';
$l['delete_threads'] = 'Paslėpti temą';
$l['move_threads'] = 'Iškelti temą';
$l['approve_threads'] = 'Patvirtinti temą';
$l['unapprove_threads'] = 'Nepatvirtinti temos';
$l['inline_go'] = 'Eiti';
$l['clear'] = 'Išvalyti';
$l['sub_forums_in'] = 'Forumai \'{1}\'';
$l['forum_rules'] = '{1} - Taisyklės';
$l['subforums'] = '<strong>Sub Forumai:</strong>';
$l['asc'] = 'did.';
$l['desc'] = 'maž.';
$l['forum_announcements'] = 'Forumo pranešimai';
$l['sticky_threads'] = 'Svarbios temos';
$l['normal_threads'] = 'Standartinės temos';
$l['icon_dot'] = 'Turi tavo rašytų pranešimų. ';
$l['icon_no_new'] = 'Nėra naujų pranešimų.';
$l['icon_new'] = 'Nauji pranešimai.';
$l['icon_hot'] = ' Karšta tema.';
$l['icon_lock'] = ' Užrakinta tema.';
$l['attachment_count'] = 'Ši tema turi 1 priedą.';
$l['attachment_count_multiple'] = 'Ši tema turi {1} priedus.';
$l['rss_discovery_forum'] = 'Naujausios temos {1}';
$l['forum_unapproved_posts_count'] = 'Yra {1} nepatvirtinti pranešimai šiame forume.';
$l['forum_unapproved_post_count'] = 'Yra 1 nepatvirtintas pranešimas šiame forume.';
$l['forum_unapproved_threads_count'] = 'Yra {1} nepatvirtintų temų šiame forume.';
$l['forum_unapproved_thread_count'] = 'Yra 1 nepatvirtinta tema šiame forume.';
$l['thread_unapproved_posts_count'] = 'Yra {1} nepatvirtinti pranešimai šioje temoje.';
$l['thread_unapproved_post_count'] = 'Yra 1 nepatvirtintas pranešimas šioje temoje.';
$l['page_selected'] = 'Visos <strong>{1}</strong> temos šiame puslapyje yra pasirinktos.';
$l['all_selected'] = 'Visos <strong>{1}</strong> temos šiame forume yra pasirinktos.';
$l['select_all'] = 'Pasirinkti visas <strong>{1}</strong> temas šiame forume.';
$l['clear_selection'] = 'Išvalyti pasirinkimą.';
$l['error_containsnoforums'] = 'Atsiprašome, šiame forume kolkas nėra sukurtų sub forumų.';
$l['inline_edit_description'] = '(Spausti ir palaikyti norint redaguoti)';
