<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sun, 24 Jul 2016 07:59:15 +0000
// --------------------------------------------------------------------------------

$l['gomobile_settings_mobile_name_title'] = 'Forumo pavadinimas';
$l['gomobile_settings_mobile_name'] = 'Naudokite šį nustatymą, sutrumpinti tiek savo antraštę ir naršymo kelio (navigacijos) tekstą. Jūs galite naudoti visą HTML formatavimą.';
$l['gomobile_settings_redirect_enabled_title'] = 'Įjungti Portalo nukreipimą?';
$l['gomobile_settings_redirect_enabled'] = 'Įjungti arba išjungti Mobilios svetainės būtybę peradresuoti. Įgalinus šią parinktį, bus automatiškai nukreipiami vartotojai, kurie lankosi su portale su savo mobiliaisiais.';
$l['gomobile_settings_redirect_location_title'] = 'Nukreipimo vieta';
$l['gomobile_settings_redirect_location'] = 'Įveskite vietą (santykinė), kur jūs norėtumėte nukreipti vartotojus. Ignoruoti tai jei peradresavimas aukščiau nėra įjungtas.';
$l['gomobile_settings_theme_id_title'] = 'Temos ID';
$l['gomobile_settings_theme_id'] = 'Įveskite TID (temos ID) mobiliai versijai žemiau. Tai naudojama perjungti vartotoją į mobilią versiją.';
$l['gomobile_settings_permstoggle_title'] = 'Naudoti temos teises?';
$l['gomobile_settings_permstoggle'] = 'Enable this setting to use the theme-specific usage permissions. If disabled, all groups will be able to use GoMobile. Selecting NO also saves a query, and is recommended unless you require theme permissions.';
$l['gomobile_settings_homename_title'] = 'Pagrindinio puslapio pavadinimas';
$l['gomobile_settings_homename'] = 'This is the text that will appear in the footer of GoMobile in place of the home link. It is recommended that you keep this to as few charaters as possible.';
$l['gomobile_settings_homelink_title'] = 'Pagrindinio puslapio nuoroda';
$l['gomobile_settings_homelink'] = 'Below is the link that appears in the footer of GoMobile.';
$l['gomobile_settings_strings_title'] = 'Vartotojo Agento eilutės';
$l['gomobile_settings_strings'] = 'Separated by a new line, enter the strings you wish to check for and then send to the mobile theme. You should not normally need to adjust this.';
$l['gomobile_mobile_version'] = 'Mobili versija';
$l['gomobile_switch_full'] = 'Perjungti pilną versiją';
$l['gomobile_redirect_notice'] = 'Nukreipimo pranešimas';
$l['gomobile_posted_from'] = 'Parašyta iš mobilaus įrenginio';
$l['gomobile_ucp'] = 'Vartotojo pultas';
$l['gomobile_mcp'] = 'Moder.';
$l['gomobile_acp'] = 'Admin.';
$l['gomobile_pms'] = 'AŽ';
$l['gomobile_logout'] = 'Atsijungti';
$l['gomobile_last'] = 'Paskutinis';
$l['gomobile_lastby'] = 'Paskutinį parašė:';
$l['gomobile_post_edit'] = 'Redaguoti';
$l['gomobile_post_delete'] = 'Trinti';
$l['gomobile_post_quote'] = 'Cituoti';
$l['gomobile_post_warn'] = 'Įspėti';
$l['gomobile_post_pm'] = 'AŽ';
$l['gomobile_page'] = 'Puslapis:';
$l['gomobile_of'] = 'iš';
$l['gomobile_copyrights'] = '';
$l['gomobile_showsig'] = 'Rodyti tavo parašą?';
$l['gomobile_disablesmilies'] = 'Išjungti emocijas šioje žinutėje?';
$l['gomobile_savecopy'] = 'Išsaugoti kopiją?';
$l['gomobile_receipt'] = 'Sekti kaip gavėjas perskaito tai?';
$l['gomobile_modclose'] = 'Uždaryti šią temą?';
$l['gomobile_modstick'] = 'Prilipinti šią temą?';
$l['gomobile_send'] = 'Siųsti';
$l['gomobile_unreadreports'] = 'Moder. pranešimas: Neperskaityta įspėtų pranešimų';
$l['gomobile_bbclosed'] = 'Jūsų lenta nustatyta kaip uždaryta.';
$l['gomobile_nosubs'] = 'Nėra prenumeratų.';
$l['gomobile_newsubs'] = 'Nauji pranešimai prenumeruojamose temose';
$l['gomobile_redirect_portal'] = 'Jūsų administratorius pasirinko išjungti portalo žiūrėjimą naršant mobilioje versijoje, būtite nukreiptas į kitą puslapį ...';
$l['gomobile_use_mobile_version'] = 'Naudokite mobilią versiją, jei apsilankė iš mobiliojo prietaiso?';
$l['gomobile_clear_cookies'] = 'valyti slapukus';
$l['gomobile_switched_version'] = 'Keičiamos versijos.<br />Palaukite kol grąžinsime jus atgal...';
$l['gomobile_lastpost'] = 'Paskutinis pranešimas:';
$l['gomobile_orderby'] = 'Rikiuoti pagal:';
$l['gomobile_forum'] = 'Forumas:';
$l['gomobile_by'] = 'Nuo:';
$l['gomobile_jump_fpost'] = 'Pirmas pranešimas';
$l['gomobile_jump_lpost'] = 'Paskutinis pranešimas';
$l['gomobile_votes'] = 'Balsai';
$l['gomobile_error_message'] = 'Jūs neturite teisės pasiekti šio puslapio. Pabandykite prisijungti žemiau, o jei tai nepadeda, gal jūs neturite teisės būti čia.';
$l['gomobile_home'] = 'Pradžia';
$l['gomobile_ucp_username'] = 'Vartotojo vardas:';
$l['gomobile_ucp_avatar'] = 'Avataras:';
$l['gomobile_ucp_inbox'] = 'Pašto dėžutė';
$l['gomobile_pm_reply'] = 'Atsakyti';
$l['gomobile_pm_delete'] = 'Trinti';
$l['gomobile_pm_forward'] = 'Persiųsti';
$l['gomobile_pm_replyall'] = 'Atsakyti visiems';
$l['gomobile_mcp_until'] = '- Iki:';
$l['gomobile_mcp_reason'] = 'Priežastis:';
$l['gomobile_mcp_controls'] = 'Valdymas';
$l['gomobile_mcp_pid'] = 'Pranešimas #';
$l['gomobile_mcp_in'] = ' in ';
