<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 19:18:31 +0000
// --------------------------------------------------------------------------------

$l['d1_name'] = 'Vartotojo registracija';
$l['d1_desc'] = 'Privilegijos ir lengvatos vartotojo registracijai.';
$l['d1_document'] = 'Kai kurios šiame forume esančios dalys gali reikalauti būti prisijungus ir prisiregistruoti. Registracija yra nemokama ir trunka keletą minučių.
<br /><br />Jūs esate raginami registruotis; kai jūs užsiregistruosite, galėsite rašyti pranešimus, nustatyti savo prioritetus ir palaikyti profilį.
<br /><br />Kai kurios iš funkcijų, kurios paprastai reikalauja registracijos, yra prenumeratos, stiliai, gauti savo asmeninę užrašinę ir t.t.';
$l['d2_name'] = 'Atnaujinamas profilis';
$l['d2_desc'] = 'Pakeitus duomenis šiuo metu įrašo.';
$l['d2_document'] = 'Tam tikru savo viešnagės metu metu, galite nuspręsti, ką jums reikia atnaujinti tam tikrą informaciją, pavyzdžiui, jūsų greitųjų žinučių informacija, slaptažodį, arba savo elektroninio pašto adresą. Jūs galite pakeisti šią informaciją iš savo vartotojo valdymo pulte. Patekti į šį valdymo pultą, tiesiog paspauskite ant viršutiniame dešiniajame kampe bet kokiam puslapyje pavadinimu "Vartotojas KP" nuorodą. Iš ten, tiesiog pasirinkti atitinkamą nuorodą skiltyje "Jūsų profilis" ir pakeisti ar atnaujinti norimus daiktus, tada pereikite prie spustelėkite mygtuką pateikti esantį puslapio apačioje pakeitimai įsigaliotų.';
$l['d3_name'] = 'Slapukų naudojimas su MyBB';
$l['d3_desc'] = 'MyBB naudoja sausainėlius, renka tam tikrą informaciją apie registruotus vartotojus.';
$l['d3_document'] = 'MyBB naudoja sausainėlius prisijungimo informacijai, jei esate registruotas, ir paskutinio Jūsų apsilankymo jei nesate.
<br /><br />Slapukai yra maži tekstiniai dokumentai saugomi jūsų kompiuteryje; kurias šiame forume nustatyti slapukai gali būti naudojami tik šioje svetainėje ir nekelia pavojaus saugumui.
<br /><br />Slapukai šiame forume taip pat stebėti konkrečias temas perskaitėte ir kada paskutinį kartą juos skaityti.
<br /><br />Išvalyti visus šio nustatytos formos slapukus, jūs galite spustelėdami <a href="misc.php?action=clearcookies&amp;my_post_key={1}">čia</a>.';
$l['d4_name'] = 'Prisijungimas ir atsijungimas';
$l['d4_desc'] = 'Kaip prisijungti ir atsijungti.';
$l['d4_document'] = 'Kai prisijungiate, galite nustatyti slapuką jūsų kompiuteryje, kad jūs galite naršyti forumuose be įvesti savo vartotojo vardą ir slaptažodį kiekvieną kartą. Atsijungti išvalo kad slapukas užtikrinti niekas kitas gali naršyti forumą kaip jūs.
<br /><br />Norėdami prisijungti, spauskite prisijungimo nuorodą viršuje dešinėje kampe forume. Norėdami išsiregistruoti, atsijunkite nuorodą į tą pačią vietą. Tuo atveju, jei jūs negalite išeiti, kliringo slapukus jūsų kompiuteryje imsis tokį patį poveikį.';
$l['d5_name'] = 'Naujos temos kūrimas';
$l['d5_desc'] = 'Pradėti naują temą į forume.';
$l['d5_document'] = 'Kai jūs einate į forumą jus domina ir jūs norite sukurti naują temą (arba tema), tiesiog pasirinkti viršuje ir apačioje forumuose pavadintą "naują temą" mygtuką. Prašome atkreipti dėmesį, kad jūs negalite turėti leidimą skelbti naują temą kiekvienoje forume administratorius gali būti ribojamas komandiravimo šio forumo darbuotojams arba archyvuojami forumą visiškai.';
$l['d6_name'] = 'Atsakyti temoje';
$l['d6_desc'] = 'Atsakymas į temą forume.';
$l['d6_document'] = 'Per savo vizitą, žinoma, galite susidurti su tema, į kuria norėsite parašyti atsakymą. Norėdami tai padaryti, tiesiog spustelėkite "Naujas Atsakymas" mygtuką apačioje ar viršuje pokalbio. Prašome atkreipti dėmesį, kad jūsų administratorius gali būti ribojamas komandiravimo tam tikriems asmenims toje konkrečioje forume.
<br /><br />Be to, iš forumo moderatorius gali uždarė siūlai reiškia, kad vartotojai negalite atsakinėti į ją. Nėra būdas vartotojui atidaryti tokį siūlą be moderatoriaus ar administratoriaus pagalba.';
$l['d7_name'] = 'MyCode';
$l['d7_desc'] = 'Sužinokite, kaip naudoti MyCode savo pranešimuose.';
$l['d7_document'] = 'You can use MyCode, a simplified version of HTML, in your posts to create certain effects.
<p><br />[b]This text is bold[/b]<br />&nbsp;&nbsp;&nbsp;<b>This text is bold</b>
<p>[i]This text is italicized[/i]<br />&nbsp;&nbsp;&nbsp;<i>This text is italicized</i>
<p>[u]This text is underlined[/u]<br />&nbsp;&nbsp;&nbsp;<u>This text is underlined</u>
<p>[s]This text is struck out[/s]<br />&nbsp;&nbsp;&nbsp;<strike>This text is struck out</strike>
<p><br />[url]http://www.example.com/[/url]<br />&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">http://www.example.com/</a>
<p>[url=http://www.example.com/]Example.com[/url]<br />&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">Example.com</a>
<p>[email]example@example.com[/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">example@example.com</a>
<p>[email=example@example.com]E-mail Me![/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">E-mail Me!</a>
<p>[email=example@example.com?subject=spam]E-mail with subject[/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com?subject=spam">E-mail with subject</a>
<p><br />[quote]Quoted text will be here[/quote]<br />&nbsp;&nbsp;&nbsp;<quote>Quoted text will be here</quote>
<p>[code]Text with preserved formatting[/code]<br />&nbsp;&nbsp;&nbsp;<code>Text with preserved formatting</code>
<p><br />[img]http://www.php.net/images/php.gif[/img]<br />&nbsp;&nbsp;&nbsp;<img src="http://www.php.net/images/php.gif">
<p>[img=50x50]http://www.php.net/images/php.gif[/img]<br />&nbsp;&nbsp;&nbsp;<img src="http://www.php.net/images/php.gif" width="50" height="50">
<p><br />[color=red]This text is red[/color]<br />&nbsp;&nbsp;&nbsp;<font color="red">This text is red</font>
<p>[size=3]This text is size 3[/size]<br />&nbsp;&nbsp;&nbsp;<font size="3">This text is size 3</font>
<p>[font=Tahoma]This font is Tahoma[/font]<br />&nbsp;&nbsp;&nbsp;<font face="Tahoma">This font is Tahoma</font>
<p><br />[align=center]This is centered[/align]<div align="center">This is centered</div>
<p>[align=right]This is right-aligned[/align]<div align="right">This is right-aligned</div>
<p><br />[list]<br />[*]List Item #1<br />[*]List Item #2<br />[*]List Item #3<br />[/list]<br /><ul><li>List item #1</li><li>List item #2</li><li>List Item #3</li>
</ul>
<p>You can make an ordered list by using [list=1] for a numbered, and [list=a] for an alphabetical list.</p>';
