<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : rootadmin
// Last edited date : Thu, 31 Mar 2016 09:26:50 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Forumo statistika';
$l['new_posts'] = 'Forumas turi nauju įrašų';
$l['no_new_posts'] = 'Forumas neturi naujų įrašų';
$l['forum_locked'] = 'Forumas užrakintas';
$l['forum_unapproved_posts_count'] = 'Yra {1} nepatvirtinti įrašai šiame forume.';
$l['forum_unapproved_post_count'] = 'Yra 1 nepatvirtintas įrašas šiame forume.';
$l['forum_unapproved_threads_count'] = 'Yra {1} nepatvirtinta tema šiame forume.';
$l['forum_unapproved_thread_count'] = 'Yra 1 nepatvirtinta tema šiame forume.';
$l['markread'] = 'Žymeti visus forumus kaip skaitytus';
$l['forumteam'] = 'Komanda';
$l['forumstats'] = 'Forumo statistika';
$l['todays_birthdays'] = 'Gimtadienį švenčia';
$l['birthdayhidden'] = 'Paslėpti';
$l['quick_login'] = 'Greitas prisijungimas:';
$l['index_logout'] = 'Atsijungti';
$l['private_messages'] = 'Asmeninės žinutės';
$l['pms_new'] = 'Turite {1} naują žinutę nuo paskutinio apsilankymo.';
$l['pms_unread_total'] = '(Turite {1} neskaitytas(-ą) žinutes(-ę) ir {2} žinutes(-ę) visuose Jūsų aplankuose.)';
$l['stats_posts_threads'] = 'Lanktytojai sukūrė {1} įrašų(-us) {2} temose(-ų).';
$l['stats_numusers'] = 'Registruotų vartotojų {1}';
$l['stats_newestuser'] = 'Naujausias narys, <b>{1}</b>';
$l['stats_mostonline'] = 'Daugiausia prisijungusių vienu metu buvo {1}, {2} {3}';
$l['whos_online'] = 'Šiuo metu prisijungę';
$l['complete_list'] = 'Visas sąrašas';
$l['online_online_plural'] = 'vartotojai';
$l['online_online_singular'] = 'vartotojas';
$l['online_member_plural'] = 'vartotojai';
$l['online_member_singular'] = 'vartotojas';
$l['online_anon_plural'] = 'yra';
$l['online_anon_singular'] = 'yra';
$l['online_guest_plural'] = 'svečiai';
$l['online_guest_singular'] = 'svečias';
$l['online_note'] = '{1} {2} prisijungęs pastariasias {3} minutes ({4} {5}, {6} iš jų {7} nematomi, ir {8} {9}).';
$l['subforums'] = '<strong>Sub Forumai:</strong>';
