<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 16:04:44 +0000
// --------------------------------------------------------------------------------

$l['nav_group_management'] = '{1} Grupės valdymas';
$l['nav_join_requests'] = 'Prisijungimo užklausos';
$l['nav_group_memberships'] = 'Grupės dalyviai';
$l['not_leader_of_this_group'] = 'Atsiprrašome, bet jūs nesate šios grupės lyderis.';
$l['invalid_group'] = 'Ši vartotojų grupė neegzistuoja.';
$l['pending_requests'] = 'Laukiančios prisijungimo užklausos.';
$l['num_requests_pending'] = 'Šiuo metu yra <strong>{1}</strong> nepatvirtintos prisijungimo užklausos, prie šios vartotojų grupės.';
$l['group_management'] = 'Grupės valdymas';
$l['members_of'] = 'Vartotojų "{1}"';
$l['user_name'] = 'Vartotojo vardas';
$l['contact'] = 'Kontaktas';
$l['reg_date'] = 'Registruotas';
$l['post_count'] = 'Pranešimai';
$l['remove_selected'] = 'Išmesti pasirinktus vartotojus iš grupės';
$l['add_member'] = 'Pridėti vartotoją į "{1}"';
$l['add_member_submit'] = 'Pridėti vartotoją prie grupės';
$l['invite_member'] = 'Pakviesti vartotoją į "{1}"';
$l['invite_member_submit'] = 'Pakviesti vartotoją į grupę';
$l['join_requests'] = 'Prisijungimo užklausos';
$l['join_requests_title'] = 'Prisijungimo užklausos dėl "{1}"';
$l['leader'] = '(Lyderis)';
$l['reason'] = 'Priežastis';
$l['accept'] = 'Patvirtinti';
$l['ignore'] = 'Ignoruoti';
$l['decline'] = 'Atmesti';
$l['action_requests'] = 'Atlikti veiksmus';
$l['join_requests_moderated'] = 'The join requests have been moderated.<br />You will now be taken to the request listing.';
$l['no_requests'] = 'There are currently no pending join requests for this group.';
$l['no_users'] = 'Šioje grupėje vartotojų nėra.';
$l['user_added'] = 'The user has been added to the user group.';
$l['users_removed'] = 'The selected users have been removed from the user group.';
$l['group_no_members'] = 'There are currently no members in this group.<br />To return to the group management page, click <a href="usercp.php?action=usergroups">here</a>.';
$l['group_public_moderated'] = 'This user group is a public user group that anyone can join.  All join requests must be moderated by a group leader.';
$l['group_public_not_moderated'] = 'This user group is a public user group that anyone can join freely.';
$l['group_public_invite'] = 'This user group is a public user group that requires an invitation from a group leader in order to join.';
$l['group_private'] = 'This user group is a private user group.  Only users added by the group leader can be part of this group.';
$l['group_default'] = 'This user group is a core user group.';
$l['group_leaders'] = 'Group Leaders';
$l['no_users_selected'] = 'Sorry, but no users seemed to be selected for removal.<br />Please go back and select the users you want to remove from this group.';
$l['error_alreadyingroup'] = 'The user specified is already part of the user group.';
$l['error_alreadyinvited'] = 'The user specified has already been invited.';
$l['user_invited'] = 'The user has been invited to join the user group.';
$l['invite_pm_subject'] = 'You have been invited to join "{1}"';
$l['invite_pm_message'] = 'You have received an invitation to join the user group "{1}".

To join, please proceed to your [url={2}/usercp.php?action=usergroups]Group Memberships[/url] page and click \'Accept Invite\'.

This invitation does not expire.';
$l['invite_pm_message_expires'] = 'You have received an invitation to join the user group "{1}".

To join, please proceed to your [url={2}/usercp.php?action=usergroups]Group Memberships[/url] page and click \'Accept Invite\'.

This invite will expire {3} days from now.';
