<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 16:12:15 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Vartotojai';
$l['memberlist_disabled'] = 'Vartotojų sąrašo funkcija išjungta.';
$l['member_list'] = 'Vartotojai';
$l['avatar'] = 'Avataras';
$l['username'] = 'Vartotojo vardas';
$l['joined'] = 'Prisijungė';
$l['lastvisit'] = 'Paskutinis apsilankymas';
$l['posts'] = 'Pranešimų skaičius';
$l['threads'] = 'Temų skaičius';
$l['referrals'] = 'Atvedė';
$l['search_members'] = 'Ieskoti vartotojų';
$l['website'] = 'Tinklalapis';
$l['sort_by'] = 'Rikiuoti';
$l['contains'] = 'Turi:';
$l['sort_by_username'] = 'Rikiuoti pagal: Vartotojo vardą';
$l['sort_by_regdate'] = 'Rikiuoti pagal: Registracijos datą';
$l['sort_by_lastvisit'] = 'Rikiuoti pagal: Paskutinis apsilankymas';
$l['sort_by_posts'] = 'Rikiuoti pagal: Pranešimų skaičius';
$l['sort_by_threads'] = 'Rikiuoti pagal: Temų skaičius';
$l['sort_by_referrals'] = 'Rikiuoti pagal: Atvestus vartotojus';
$l['order_asc'] = 'didėjanti tvarka';
$l['order_desc'] = 'mažėjanti tvarka';
$l['asc'] = 'did';
$l['desc'] = 'maž';
$l['forumteam'] = 'Rodyti forumo komandą';
$l['advanced_search'] = 'Išplėstinė paieška';
$l['nav_memberlist_search'] = 'Paieška';
$l['search_member_list'] = 'Ieškoti vartotojų';
$l['search_criteria'] = 'Paieškos kriterijus';
$l['begins_with'] = 'prasideda';
$l['username_contains'] = 'turi';
$l['search_website'] = 'Tinklalapio URL';
$l['search_aim'] = 'AIM rodomas vardas';
$l['search_skype'] = 'Skype adresas';
$l['search_google'] = 'Google Talk adresas';
$l['search_yahoo'] = 'Yahoo! pranešėjo vardas';
$l['search_icq'] = 'ICQ numeris';
$l['search_options'] = 'Paieškos nustatymai';
$l['per_page'] = 'Rezultatų puslapyje';
$l['search'] = 'Paieška';
$l['error_no_members'] = '<p>Vartotojų nebuvo rasta pagal paieškos kriterijų.</p><p>Įveskite kitą paieškos užklausą ir bandykite dar kartą.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
