<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 18:59:11 +0000
// --------------------------------------------------------------------------------

$l['nav_register'] = 'Registruotis';
$l['nav_activate'] = 'Aktyvuoti';
$l['nav_resendactivation'] = 'Persiųsti aktyvacijos laišką';
$l['nav_lostpw'] = 'Pamiršto slaptažodžio atstatymas';
$l['nav_resetpassword'] = 'Atstatyti slaptažodį';
$l['nav_login'] = 'Prisijungti';
$l['nav_emailuser'] = 'Siųsti laišką vartotojui';
$l['nav_profile'] = 'Profilis {1}';
$l['tpp_option'] = 'Rodyti {1} temų viename puslapyje';
$l['ppp_option'] = 'Rodyti {1} pranešimų viename puslapyje';
$l['account_activation'] = 'Prodilio aktyvacija';
$l['activate_account'] = 'Aktyvuoti profilį';
$l['activation_code'] = 'Aktyvacijos kodas:';
$l['email_user'] = 'Siųsti{1} el. laišką';
$l['email_subject'] = 'El. laiško tema';
$l['email_message'] = 'El. laiško žinutė';
$l['send_email'] = 'Siųsti el. laišką';
$l['error_hideemail'] = 'Gavėjas nusprendė paslėpti savo el. pašto adresą, todėl negalimą išsiųsti el. laiško.';
$l['error_no_email_subject'] = 'Reikia įvesti el. laiško temą';
$l['error_no_email_message'] = 'Reikia įvesti el. laiško žinutę';
$l['login'] = 'Prisijungti';
$l['pw_note'] = 'Primename, kad slaptažodžiai naudoja didžiąsias ir mažąsias raides. (A ir a nėra tas pats)';
$l['lostpw_note'] = 'Pamiršai slaptažodį?';
$l['lost_pw'] = 'Pamirštas profilio slaptažodis';
$l['lost_pw_form'] = 'Pamiršto slaptažodžio atstatymo forma';
$l['email_address'] = 'El. pašto adresas:';
$l['request_user_pass'] = 'Gauti prisijungimo duomenis';
$l['profile'] = 'Prodilis {1}';
$l['registration_date'] = 'Registracijos data:';
$l['date_of_birth'] = 'Gimimo data:';
$l['birthdayhidden'] = 'Paslėptas';
$l['birthday'] = 'Gimtadienis:';
$l['local_time'] = 'Vietos laikas:';
$l['local_time_format'] = '{1} at {2}';
$l['users_forum_info'] = '{1} Forumo Informacija';
$l['joined'] = 'Prisijungė:';
$l['lastvisit'] = 'Paskutinis apsilankymas:';
$l['total_posts'] = 'Viso pranešimų:';
$l['ppd_percent_total'] = '{1} prenešimų per dieną | {2} procentai visų pranešimų';
$l['total_threads'] = 'Viso temų:';
$l['tpd_percent_total'] = '{1} temųper dieną | {2} procentai visų temų';
$l['find_posts'] = 'Rasti visus pranešimus';
$l['find_threads'] = 'Rasti visas temas';
$l['members_referred'] = 'Paminėti nariai:';
$l['rating'] = 'Reitingas:';
$l['users_contact_details'] = '{1} Kontaktiniai duomenys';
$l['homepage'] = 'Namų puslapis:';
$l['pm'] = 'Privati žinutė:';
$l['send_pm'] = 'Siųsti {1}privačią žinutę.';
$l['icq_number'] = 'ICQ numeris:';
$l['aim_screenname'] = 'AIM vardas:';
$l['yahoo_id'] = 'Yahoo ID:';
$l['skype_id'] = 'Skype ID:';
$l['google_id'] = 'Google Talk ID:';
$l['avatar'] = 'Avataras:';
$l['warning_level'] = 'Įspėjimo lygis:';
$l['warn'] = 'Įspėti';
$l['away_note'] = '{1} šiuo metu pasitraukęs.';
$l['away_reason'] = 'Priežastis:';
$l['away_since'] = 'Pasitraukęs nuos:';
$l['away_returns'] = 'Grįžo:';
$l['away_no_reason'] = 'Nėra nurodyta.';
$l['ban_note'] = 'Šis forumo profilis yra uždraustas.';
$l['ban_by'] = 'Uždraudė';
$l['ban_length'] = 'Draudimo trukmė';
$l['ban_remaining'] = 'liko';
$l['users_additional_info'] = 'Papildoma informacija apie {1}';
$l['email'] = 'El. paštas:';
$l['send_user_email'] = 'Siųsti {1} el. laišką.';
$l['users_signature'] = '{1} Parašas';
$l['agreement'] = 'Registracijos sustikimas';
$l['agreement_1'] = 'Mes stengiamės redaguoti ar pašalinti bet kokius pranešimus, kuriuose yra netinkama, seksualiai orientuota, užgauli, bjauri, šmeižikiška, arba grasinanti medžiaga, kuri galėtų būti laikoma invazinė į asmens privatumą, ar kitaip pažeidžia teisės normas, neįmanoma mums peržiūrėti kiekvieną pranešimą parašė šioje diskusijų sistema. Dėl šios priežasties jūs pripažįstate, kad visi paskelbtas šioje diskusijų sistema žinutės išreiškia požiūrį ir nuomonę į originalaus pranešimo autorius ir nebūtinai šią diskusijų lentą nuomonę. Todėl mes neprisiimame atsakomybės ir negali būti laikoma atsakinga už bet kokių paskelbtų pranešimų. Mes neturime laiduotoją ar garantuoti tikslumą ir išsamumą kiekvieną pranešimą.';
$l['agreement_2'] = 'Registruodamiesi šiame diskusijų forume sutinkate, jog neplatinsite žinučių, kurios yra akivaizdžiai melagingos, netikslios, įžeidžios, skatinančios neapykantą, įkyrios, seksualinio, grasinančio ar asmens privatumą pažeidžiančio pobūdžio, taip pat bet kokios kitos informacijos, kuri galėtų pažeisti galiojančią teisę.';
$l['agreement_3'] = 'Nesilaikant šių taisyklių, gali sukelti paskyros nutraukimo, sąskaitos sustabdymo arba nuolatinis draudimas susipažinti su šių forumų. Jūsų IP adresas yra įrašomas su kiekvienu įrašu galite padaryti šią diskusiją sistemą ir yra gaunama iš forumo darbuotojams, jei reikia-bus. Jūs sutinkate, kad mes turime galimybę ir teisę ištrinti, redaguoti, ar užrakinti bet kurią sąskaitą arba žinutę bet kuriuo metu jeigu jie mano, kad būti vertinamas tinka. Jūs taip pat sutinkate, kad bet kokia informacija, kurią įvedate šioje diskusijų sistema yra saugomi duomenų bazėje, ir kad "slapukai" yra saugomi jūsų kompiuteryje išsaugoti savo prisijungimo informaciją.';
$l['agreement_4'] = 'Bet kokia jūsų pateikta informacija šiame forume nebus parodyta be jūsų sutikimo, nors forumo administratoriai negali užtikrinti, kad į forumą nebus įsilaužta ir nebus nutekinta jūsų pateikta informacija.';
$l['agreement_5'] = 'Tęsiant prisijungimo procesą jūs sutinkate su visomis viršuje išvardintomis ir kitomis administratorių specifikuotomis taisyklėmis.';
$l['registration'] = 'Registracija';
$l['required_fields'] = 'Privalomi laukai';
$l['complex_password'] = '<acronym title="Slaptažodis, kurii ilgis sudaro bent {1} simbolius ir turi didžiąsias ir mažąsias raides,bei skaičius.">Sudėtingas</acronym> Slaptažodis:';
$l['confirm_email'] = 'Patvirtinti el. paštą:';
$l['optional_fields'] = 'Neptivalomi laukai';
$l['website_url'] = 'Tavo puslapio URL:';
$l['birthdate'] = 'Gimimo data:';
$l['additional_info'] = 'Papildoma informacija';
$l['required_info'] = 'Privaloma informacija';
$l['i_agree'] = 'Sutinku';
$l['account_details'] = 'Prodilio detalės';
$l['account_prefs'] = 'Profilio nustatymai:';
$l['invisible_mode'] = 'Nerodyti manęs, prisijungusių sąraše.';
$l['allow_notices'] = 'Gauti laiškus nuo administratorių.';
$l['hide_email'] = 'Slėpti el. paštą nuo kitų vartotojų.';
$l['email_notify'] = 'Automatiškai prenumeruoti temas, kuriose rašote pranešimus.';
$l['receive_pms'] = 'Gauti privačias žinutes nuo kitų vartotojų.';
$l['pm_notice'] = 'Įspėti mane, kai gaunu privačią žinutę.';
$l['email_notify_newpm'] = 'Įspėti mane el. paštu, kai gaunu privačią žinutę.';
$l['time_offset'] = 'Laiko juosta (<acronym title="Vasaros laikas">DST</acronym> atmesti korekciją):';
$l['time_offset_desc'] = 'Jeigu gyvenate laiko juostoje, kuri skiriasi nuo šio forumo laiko, galite pasirinkti iš sąrašo žemiau.';
$l['dst_correction'] = 'Vasaros laiko pataisymas:';
$l['dst_correction_auto'] = 'Automatiškai aptikti Vasaros laiko nustatymus';
$l['dst_correction_enabled'] = 'Visada naudoti Vasaros laiko pataisymus';
$l['dst_correction_disabled'] = 'Nenaudoti Vasaros laiko pataisymų';
$l['redirect_registered_coppa_activate'] = 'Thank you for registering on {1}, {2}. Your account has successfully been created, however, as the owner of this account is under the age of 13, parental permission needs to be sought before this account can be used.<br /><br />A parent or legal guardian will need to download, fill in and submit to us a completed copy of our <a href="member.php?action=coppa_form">COPPA Compliance &amp; Permission form</a>.<br /><br />Once we receive a completed copy of this form, the account will be activated.';
$l['coppa_compliance'] = 'COPPA Compliance';
$l['coppa_desc'] = 'In order to register on these forums, we require you to verify your age to comply with <a href="http://coppa.org/" title="Children\'s Online Privacy Protection Act" target="_blank">COPPA</a>. Please enter your date of birth below.<br /><br />If you are under the age of 13, parental permission must be obtained prior to registration. A parent or legal guardian will need to download, fill in and submit to us a completed copy of our <a href="member.php?action=coppa_form" target="_blank">COPPA Compliance &amp; Permission form</a>.';
$l['hide_dob'] = 'Galite pasirinkti nerodyti savo gimimo dienos ir amžiaus, pakeisdami profilio nustatymus po registracijos.';
$l['signature'] = 'Parašas:';
$l['continue_registration'] = 'Tęsti registraciją';
$l['birthdayprivacy'] = 'Gimimo dienos privatumas:';
$l['birthdayprivacyall'] = 'Rodyti amžių ir gimimo dieną';
$l['birthdayprivacynone'] = 'Slėpti amžių ir gimimo dieną';
$l['birthdayprivacyage'] = 'Rodyti tik amžių';
$l['leave_this_field_empty'] = 'Palikite šį laukelį tuščią:';
$l['error_need_to_be_thirteen'] = 'Jūs turite būti bent 13 metų amžiaus, kad galėtumėte registruotis šiame forume.';
$l['coppa_registration'] = 'COPPA Registration Form';
$l['coppa_form_instructions'] = 'Please print this form, fill it in and either fax it to the number below or mail it to the provided mailing address.';
$l['fax_number'] = 'Fax Numeris:';
$l['mailing_address'] = 'El. pašto adresas:';
$l['account_information'] = 'Profilio informacija';
$l['parent_details'] = 'Parent / Guardian Details';
$l['full_name'] = 'Pilnas vardas:';
$l['relation'] = 'Relation:';
$l['phone_no'] = 'Telefono #:';
$l['coppa_parent_agreement'] = 'I understand that the information I have provided is truthful, that any information may be changed in the future by entering the supplied password and this user account can be removed by request.';
$l['coppa_agreement_1'] = 'Users under the age of 13 must receive permission from their parent or legal guardian in order to register on {1}.';
$l['coppa_agreement_2'] = 'A parent or legal guardian will need to download, fill in and submit to us a completed copy of our <a href="member.php?action=coppa_form" target="_blank">COPPA Compliance &amp; Permission form</a> before membership will be granted.';
$l['coppa_agreement_3'] = 'If you\'d like to, you can begin the registration process now, however the account will be inaccessible until the above compliance form is received.';
$l['error_invalid_birthday'] = 'The birthday you entered is invalid. Please enter a valid birthday.';
$l['error_awaitingcoppa'] = 'You cannot login using this account as it is still awaiting COPPA validation from a parent or guardian.<br /><br />A parent or legal guardian will need to download, fill in and submit to us a completed copy of our <a href="member.php?action=coppa_form">COPPA Compliance &amp; Permission form</a>.<br /><br />Once we receive a completed copy of this form, the account will be activated.';
$l['lang_select'] = 'Kalbos nustatymai:';
$l['lang_select_desc'] = 'If you live in a country that speaks a language other than the forums default, you may be able to select an installed, read-able language pack below.';
$l['lang_select_default'] = 'Naudoti numatytąją';
$l['submit_registration'] = 'Patvirtinti registraciją!';
$l['confirm_password'] = 'Patvirtinti slaptažodį:';
$l['referrer'] = 'Atvedęs asmuo:';
$l['referrer_desc'] = 'Jeigu į šį forumą jus atvedė kitas vartotojas, galite nurodyti jo vardą. Jeigu ne, tiesiog palikite šį laukelį tuščią.';
$l['resend_activation'] = 'Persiųsti profilio aktyvacijos duomenis';
$l['request_activation'] = 'Prašyti aktyvacijos kodo';
$l['ppp'] = 'Pranešimų puslapyje:';
$l['ppp_desc'] = 'Leidžia jums pasirinkti pranešimų skaičių rodomą viename puslapyje visose temose.';
$l['tpp'] = 'Temų puslapyje:';
$l['tpp_desc'] = 'Leidžia jums pasirinkti temų skaičių rodomą viename puslapyje visame temų sąraše.';
$l['reset_password'] = 'Atstatyti slaptažodį';
$l['send_password'] = 'Siųsti naują slaptažodį!';
$l['registration_errors'] = 'Klaidos pasirodžiusios registracijos metu:';
$l['timeonline'] = 'Praleista laiko prisijungus:';
$l['timeonline_hidden'] = '(Paslėpta)';
$l['registrations_disabled'] = 'Atsiprašome, bet šiuo metu administratorius išjungė naujų registracijų galimybę.';
$l['error_username_length'] = 'Neteisingas vartotojo vardas. Vartotojo vardas turi būti nuo {1} iki {2} simbolių.';
$l['error_stop_forum_spam_spammer'] = 'Atsiprašome, jūsų {1} sutampa su žinomu spameriu. jeigu manote, kad tai klaida, susisiekite su administratoriumi';
$l['error_stop_forum_spam_fetching'] = 'Atsiprašome, įvyko klaida, bandant jus atpažinti spamerių duomenų bazėje. Greičiausiai duomenų bazė negrąžina atsakymo. bandykite dar kartą vėliau.';
$l['none_registered'] = 'Nėra registruotų';
$l['not_specified'] = 'Nenurodyta';
$l['membdayage'] = '({1} metai (-ų))';
$l['mod_options'] = 'Moderatorius Nustatymai';
$l['edit_in_mcp'] = 'Redaguoti šį vartotoją Mod CP';
$l['ban_in_mcp'] = 'Uždrausti šį vartotoją Mod CP';
$l['purgespammer'] = 'Išvalyti brukalių';
$l['edit_usernotes'] = 'Redaguoti vartotojo pastabas Mod CP';
$l['no_usernotes'] = 'Šiuo metu nėra pastabų apie šį klientą';
$l['view_all_notes'] = 'Rodyti visus įrašus';
$l['view_notes_for'] = 'Peržiūrėti pastabas {1}';
$l['reputation'] = 'Reputacija:';
$l['reputation_vote'] = 'Įvertinti';
$l['reputation_details'] = 'Detalės';
$l['already_logged_in'] = 'Įspėjimas: Jūs prisijungęs kaip {1}.';
$l['admin_edit_in_acp'] = 'Redaguoti šį vartotoją Admin CP';
$l['admin_ban_in_acp'] = 'Uždrausti šį vartotoją Admin CP';
$l['admin_options'] = 'Administratoriaus nustatymai';
$l['redirect_registered_activation'] = 'Ačiū, kad registravotės {1}, {2}.<p> Kad užbaigtumėte registraciją, patikrinkite savo el. pašto dėžutę, ten rasite tolimesnes instrukcijas. Kol neaktyvuosite profilio, negalėsite rašyti pranešimų šiame forume.';
$l['redirect_emailupdated'] = 'El. paštas sėkmingai pakeistas.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_accountactivated'] = 'Profilis sėkmingai aktyvuotas.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_accountactivated_admin'] = 'El. paštas sėkmingai patikrintas.<br /> Ši registracija, dabar turi būti patvirtinta administratoriaus. Iki tol negalėsite rašyti pranešimų šiame forume.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_registered'] = 'Ačiū, kad registravotės {1}, {2}.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_registered_admin_activate'] = 'Ačiū, kad registravotės {1}, {2}.<br />Ši registracija, dabar turi būti patvirtinta administratoriaus. Iki tol negalėsite rašyti pranešimų šiame forume.';
$l['redirect_loggedout'] = 'Sėkmingai atsijungėte.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_alreadyloggedout'] = 'Jūs esate atsijungęs arba kolkas nebuvote prisijungęs.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_lostpwsent'] = 'Dėkojame, visi profiliai, susiję su šiuo elektroninio pašto adresu jau išsiųsti el. laišku su informacija apie tai, kaip atstatyti slaptažodį.<br /><br />Būsite perkeltas į pagrindinį puslapį.';
$l['redirect_activationresent'] = 'Aktyvacijos laiškas buvo persiųstas.';
$l['redirect_passwordreset'] = 'Dėkojame, profilio slaptažodis pakeistas. Atsitiktinai sugeneruotas slaptažodis nusiųstas į jūsų el. pašto dėžutę.';
$l['redirect_memberrated'] = 'Vartotojas sėkmingai reitinguotas.';
$l['redirect_registered_passwordsent'] = 'Atsitiktinai sugeneruotas slaptažodis nusiųstas į jūsų el. pašto dėžutę. Prieš prisijungiat į šį forumą, patikrinkite savo el. pašto dėžutę.';
$l['redirect_validated'] = 'Dėkojame, jūsų paskyra buvo patvirtinta.<br />Būsite perkeltas į pagrindinį puslapį.';
$l['error_activated_by_admin'] = 'You cannot resend your account activation email as all registrations must be approved by an Administrator.';
$l['error_alreadyregistered'] = 'Sorry, but our system shows that you have already registered on these forums and the registration of multiple accounts has been disabled.';
$l['error_alreadyregisteredtime'] = 'We cannot process your registration because there has already been {1} new registration(s) from your ip address in the past {2} hours. Please try again later.';
$l['error_badlostpwcode'] = 'You seem to have entered an invalid password reset code. Please re-read the email you were sent or contact the forum administrators for more help.';
$l['error_badactivationcode'] = 'You have entered an invalid account activation code. To resend all activation emails to the email address on file, please click <a href="member.php?action=resendactivation">here</a>.';
$l['error_alreadyactivated'] = 'It appears your account is already activated or does not require email verification.';
$l['error_alreadyvalidated'] = 'Your email have already been validated.';
$l['error_nothreadurl'] = 'Your message does not contain the URL of the thread. Please use the "send to friend" feature for it\'s intended purpose.';
$l['error_bannedusername'] = 'You have entered a username that is banned from registration.  Please choose another username.';
$l['error_notloggedout'] = 'Your user ID could not be verified to log you out.  This may have been because a malicious Javascript was attempting to log you out automatically.  If you intended to log out, please click the Log Out button at the top menu.';
$l['error_regimageinvalid'] = 'The image verification code that you entered was incorrect. Please enter the code exactly how it appears in the image.';
$l['error_regimagerequired'] = 'Please fill out the image verification code to continue the login process. Please enter the code exactly how it appears in the image.';
$l['error_spam_deny'] = 'Our systems detect that you may be a spammer and therefore you have been denied registration. If you feel this is a mistake, please contact the Administrator.';
$l['error_spam_deny_time'] = 'Our systems detect that you may be a spammer and therefore you have been denied registration.  Registration must take a minimum time of {1} seconds to prevent automated signups, you registered in {2} seconds. If you feel this is a mistake, please contact the Administrator.';
$l['js_validator_no_username'] = 'You must enter a username';
$l['js_validator_invalid_email'] = 'You need to enter a valid email address';
$l['js_validator_email_match'] = 'You need to enter the same email address again';
$l['js_validator_no_image_text'] = 'You need to enter the text in the image above';
$l['js_validator_no_security_question'] = 'You need to enter the answer to the question above';
$l['js_validator_password_matches'] = 'The passwords you enter must match';
$l['js_validator_password_complexity'] = 'Checking password complexity';
$l['js_validator_password_length'] = 'Your password must be {1} or more characters long';
$l['js_validator_not_empty'] = 'You must select or enter a value for this field';
$l['js_validator_checking_username'] = 'Checking if username is available';
$l['js_validator_username_length'] = 'Usernames must be between {1} and {2} characters long';
$l['js_validator_checking_referrer'] = 'Checking if referrer username exists.';
$l['js_validator_captcha_valid'] = 'Checking whether or not you entered the correct image verification code.';
$l['security_question'] = 'Saugumo klausimas';
$l['question_note'] = 'Atsakykite į pateiktą klausimą.';
$l['error_question_wrong'] = 'Atsakymas, kurį įvedėte į saugumo klausimą yra neteisingas. Bandykite dar kartą.';
$l['subscription_method'] = 'Numatytas temos prenumeravimo režimas:';
$l['no_auto_subscribe'] = 'Neprenumeruoti';
$l['no_subscribe'] = 'Nėra pranešimų';
$l['instant_email_subscribe'] = 'Momentinis el. pašto pranešimas';
$l['instant_pm_subscribe'] = 'Momentinis PM pranešimas';
$l['remove_from_buddy_list'] = 'Pašalinti iš draugų sąrašo';
$l['add_to_buddy_list'] = 'Pridėti į draugų sąrašą';
$l['remove_from_ignore_list'] = 'Pašalinti iš ignoruojamų sąrašo';
$l['add_to_ignore_list'] = 'Pridėti prie ignorujamų sąrašo';
$l['report_user'] = 'Pranešti apie vartotoją';
$l['newregistration_subject'] = 'Nauja registracija {1}';
$l['newregistration_message'] = '{1},

Yra naujas vartotojas {2} kuris laukia administratoriaus patvirtinimo.

Vartotojo vardas: {3}

Ačiū,
{2} komanda';
