<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 18:59:11 +0000
// --------------------------------------------------------------------------------

$l['click_no_wait'] = 'Spauskite čia, jei nenorite laukti ilgiau.';
$l['redirect_return_forum'] = '<br /><br />Arba, <a href="{1}">Grįžkite į forumą</a>.';
$l['redirect_emailsent'] = 'Jūsų el, laiškas sėkmingai išsiųstas.';
$l['redirect_loggedin'] = 'Jūs sėkmingai prisijungėte.<br />Dabar būsite nukreiptas į ten iš kur atėjote.';
$l['error_invalidpworusername'] = 'Įvedėte neteisingą vartotojo vardą arba slaptažodį. <br /><br />Jei pamiršote slaptažodį <a href="member.php?action=lostpw">galite gauti naują</a>.';
$l['error_invalidpworusername1'] = 'Įvedėte neteisingą vartotojo vardą arba slaptažodį. <br /><br />Jei pamiršote slaptažodį <a href="member.php?action=lostpw">galite gauti naują</a>.';
$l['error_invalidpworusername2'] = 'Įvedėte neteisingą vartotojo vardą arba slaptažodį. <br /><br />Jei pamiršote slaptažodį <a href="member.php?action=lostpw">galite gauti naują</a>.';
$l['error_incompletefields'] = 'Atrodo palikote vieną ar daugiau privalomą lauką tuščią. Prašome grįžti atgal ir užpildyti tuščius laukus.';
$l['error_alreadyuploaded'] = 'This post already contains an attachment with the same name. Please rename the file and upload it again. Alternatively you may click "Update Attachment".';
$l['error_alreadyuploaded_perm'] = 'This post already contains an attachment with the same name. Please either remove the existing file or rename the file and upload it again.';
$l['error_nomessage'] = 'Atsiprašome, negalime tęsti, nes įvedėte neteisingai įvedėte žinutę. Grįžkite atgal ir pataisykite.';
$l['error_invalidemail'] = 'Įvedėte neteisingą el. pašto adresą.';
$l['error_nomember'] = 'Nurodytas vartotojas neteisingas arba neegzistuoja.';
$l['error_maxposts'] = 'I\'m sorry, but your daily post limit has been exceeded.  Please wait till tomorrow to post further or contact your administrator.<br /><br />The maximum amount of posts you may make in a day is {1}';
$l['error_nohostname'] = 'No hostname could be found for the IP you entered.';
$l['error_invalidthread'] = 'The specified thread does not exist.';
$l['error_invalidpost'] = 'The specified post does not exist.';
$l['error_invalidannouncement'] = 'The specified announcement does not exist.';
$l['error_invalidattachment'] = 'The specified attachment does not exist.';
$l['error_invalidforum'] = 'Invalid forum';
$l['error_closedinvalidforum'] = 'You may not post in this forum because either the forum is closed, it is a redirect to another webpage, or it is a category.';
$l['error_attachtype'] = 'The type of file that you attached is not allowed. Please remove the attachment or choose a different type.';
$l['error_attachsize'] = 'The file you attached is too large. The maximum size for that type of file is {1} kilobytes.';
$l['error_uploadempty'] = 'The file specified is empty.';
$l['error_uploadsize'] = 'The size of the uploaded file is too large.';
$l['error_uploadfailed'] = 'The file upload failed. Please choose a valid file and try again. ';
$l['error_uploadfailed_detail'] = 'Error details: ';
$l['error_uploadfailed_php1'] = 'PHP returned: Uploaded file exceeded upload_max_filesize directive in php.ini.  Please contact your forum administrator with this error.';
$l['error_uploadfailed_php2'] = 'The uploaded file exceeded the maximum file size specified.';
$l['error_uploadfailed_php3'] = 'The uploaded file was only partially uploaded.';
$l['error_uploadfailed_php4'] = 'No file was uploaded.';
$l['error_uploadfailed_php6'] = 'PHP returned: Missing a temporary folder.  Please contact your forum administrator with this error.';
$l['error_uploadfailed_php7'] = 'PHP returned: Failed to write the file to disk.  Please contact your forum administrator with this error.';
$l['error_uploadfailed_phpx'] = 'PHP returned error code: {1}.  Please contact your forum administrator with this error.';
$l['error_uploadfailed_nothingtomove'] = 'An invalid file was specified, so the uploaded file could not be moved to its destination.';
$l['error_uploadfailed_movefailed'] = 'There was a problem moving the uploaded file to its destination.';
$l['error_uploadfailed_lost'] = 'The attachment could not be found on the server.';
$l['error_emailmismatch'] = 'The email addresses you entered do not match. Please go back and try again';
$l['error_nopassword'] = 'You did not enter a valid password.';
$l['error_usernametaken'] = 'The username you have chosen is already registered. If you have previously registered on these forums, please <a href="member.php?action=login">login</a>.';
$l['error_nousername'] = 'You did not enter a username.';
$l['error_invalidusername'] = 'The username you have entered appears to be invalid.';
$l['error_invalidpassword'] = 'The password you entered is incorrect. If you have forgotten your password, click <a href="member.php?action=lostpw">here</a>. Otherwise, go back and try again.';
$l['error_postflooding'] = 'We are sorry but we cannot process your post. The administrator has specified you are only allowed to post once every {1} seconds.';
$l['error_nopermission_guest_1'] = 'Jūs arba neprisijungęs arba neturite leidimo peržiūrėti šį puslapį. Tai gali būti dėl vienos iš šių priežasčių:';
$l['error_nopermission_guest_2'] = 'Jūs nesate prisijungęs arba registruotas. Prašome naudokite formą šio puslapio apačioje prisijungti.';
$l['error_nopermission_guest_3'] = 'Jūs neturite teisės pasiekti šio puslapio. Ar Jūs bandote prieiti prie administracinių puslapių ar išteklių? Patikrinkite forumo taisykles, ar jums leidžiama atlikti šį veiksmą.';
$l['error_nopermission_guest_4'] = 'Jūsų paskyra gali būti išjungta administratoriaus, arba ji laukia aktyvavimo.';
$l['error_nopermission_guest_5'] = 'You have accessed this page directly rather than using appropriate forms or links.';
$l['login'] = 'Login';
$l['need_reg'] = 'Need to register?';
$l['forgot_password'] = 'Forgotten your password?';
$l['error_nopermission_user_1'] = 'You do not have permission to access this page. This could be because of one of the following reasons:';
$l['error_nopermission_user_ajax'] = 'You do not have permission to access this page.';
$l['error_nopermission_user_2'] = 'Your account has either been suspended or you have been banned from accessing this resource.';
$l['error_nopermission_user_3'] = 'You do not have permission to access this page. Are you trying to access administrative pages or a resource that you shouldn\'t be? Check in the forum rules that you are allowed to perform this action.';
$l['error_nopermission_user_4'] = 'Your account may still be awaiting activation or moderation.';
$l['error_nopermission_user_5'] = 'You have accessed this page directly rather than using appropriate forms or link.';
$l['error_nopermission_user_resendactivation'] = 'Resend Activation Code';
$l['error_nopermission_user_username'] = 'You are currently logged in with the username: \'{1}\'';
$l['logged_in_user'] = 'Logged In User';
$l['error_too_many_images'] = 'Too Many Images.';
$l['error_too_many_images2'] = 'We are sorry, but we cannot process your post because it contains too many images. Please remove some images from your post to continue.';
$l['error_too_many_images3'] = '<b>Note:</b> The maximum amount of images per post is';
$l['error_attach_file'] = 'Error Attaching File';
$l['please_correct_errors'] = 'Please correct the following errors before continuing:';
$l['error_reachedattachquota'] = 'Sorry, but you cannot attach this file because you have reached your attachment quota of {1}';
$l['error_maxattachpost'] = 'Sorry but you cannot attach this file because you have reached the maximum number of attachments allowed per post of {1}';
$l['error_invaliduser'] = 'The specified user is invalid or does not exist.';
$l['error_invalidaction'] = 'Invalid action';
$l['error_messagelength'] = 'Sorry, your message is too long and cannot be posted. Please try shortening your message and try again.';
$l['error_message_too_short'] = 'Sorry, your message is too short and cannot be posted.';
$l['failed_login_wait'] = 'You have failed to login within the required number of attempts. You must now wait {1}h {2}m {3}s before you can login again.';
$l['failed_login_again'] = '<br />You have <strong>{1}</strong> more login attempts.';
$l['error_max_emails_day'] = 'You cannot use the \'Send Thread to a Friend\' or the \'Email User\' features because you\'ve already used up your allocated quota of sending {1} messages in the past 24 hours.';
$l['attachments_disabled'] = 'You cannot use the attachment system as it has been disabled by the Administrator.';
$l['emailsubject_lostpw'] = 'Slaptažodžio keitimas {1}';
$l['emailsubject_passwordreset'] = 'Naujas slaptažodis {1}';
$l['emailsubject_subscription'] = 'Nauja žinutė temoje {1}';
$l['emailsubject_randompassword'] = 'Jūsų spaltažodis {1}';
$l['emailsubject_activateaccount'] = 'Paskyros aktyvavimas {1}';
$l['emailsubject_forumsubscription'] = 'Nauja tema {1}';
$l['emailsubject_reportpost'] = 'Praneįtas pranešimas {1}';
$l['emailsubject_reportprofile'] = 'Pranešta apie vartotoją {1}';
$l['emailsubject_reportreputation'] = 'Pranešta apie reputaciją {1}';
$l['emailsubject_reachedpmquota'] = 'Pasiektas privačių žinučių limitas {1}';
$l['emailsubject_changeemail'] = 'El. pašto adreso keitimas {1}';
$l['emailsubject_newpm'] = 'Nauja privati žinutė {1} - {2}';
$l['emailsubject_newjoinrequest'] = 'Naujas prisijungimo prašymas {1}';
$l['emailsubject_sendtofriend'] = 'Įdomi diskusija {1}';
$l['emailsubject_changepassword'] = 'Slaptažodžio keitimas {1}';
$l['emailbit_viewthread'] = '... (apsilankykite temoje, kad galėtumėte perskaityti viską..)';
$l['email_lostpw'] = '{1},

Pabaigti paskyros slaptažodžio atstatymo fazę {2}, spauskite žemiau esančią nuorodą.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Jeigu aukščiau esanti nuoroda neveikia, spauskite nuorodą žemiau 

{3}/member.php?action=resetpassword

Jums reikės įvesti šiuos duomenis:
Prisijungimo vardas: {1}
Aktyvacijos kodas: {5}

Ačiū,
{2} Komanda';
$l['email_lostpw1'] = '{1},

Pabaigti paskyros slaptažodžio atstatymo fazę {2}, spauskite žemiau esančią nuorodą.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Jeigu aukščiau esanti nuoroda neveikia, spauskite nuorodą žemiau 

{3}/member.php?action=resetpassword

Jums reikės įvesti šiuos duomenis:
El. pašto adresas
Aktyvacijos kodas: {5}

Ačiū,
{2} Komanda';
$l['email_lostpw2'] = '{1},

Pabaigti paskyros slaptažodžio atstatymo fazę {2}, spauskite žemiau esančią nuorodą.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Jeigu aukščiau esanti nuoroda neveikia, spauskite nuorodą žemiau 

{3}/member.php?action=resetpassword

Jums reikės įvesti šiuos duomenis:
Prisijungimo vardas: {1} (arba el. pašto adresas)
Aktyvacijos kodas: {5}

Ačiū,
{2} Komanda';
$l['email_reportpost'] = '{1} from {2} has reported the following post:

{3}
{4}/{5}

The reason this user gave for reporting this post:
{6}

This message has been sent to all moderators of this forum, or all administrators and super moderators if there are no moderators.

Please check this post out as soon as possible.';
$l['email_reportprofile'] = '{1} from {2} has reported the following user:

{3}
{4}/{5}

The reason this user gave for reporting this user:
{6}

This message has been sent to all moderators of this forum, or all administrators and super moderators if there are no moderators.

Please check this user out as soon as possible.';
$l['email_reportreputation'] = '{1} from {2} has reported the following reputation:

{3}
{4}/{5}

The reason this user gave for reporting this reputation:
{6}

This message has been sent to all moderators of this forum, or all administrators and super moderators if there are no moderators.

Please check this reputation out as soon as possible.';
$l['email_passwordreset'] = '{1},

Jūsų slaptažodis {2} buvo pakeistas.

Jūsų naujas slaptažodis: {3}

Šis slaptažodis reikalingas prisijungti prie forumo, kai tik prisijungsite, pasikeiskite jį vartotojo pulte.

Ačiū,
{2} Komanda';
$l['email_randompassword'] = '{1},

Ačiū, kad užsiregistravote {2}. Žemiau yra Jūsų prisijungimo vardas ir sugeneruotas slaptažodis. Prisijungti prie {2}, Jums reikės šių duomenų.

Prisijungimo vardas: {3}
Slaptažodis: {4}

Rekomenduojame pasikeisti slaptažodį iškarto kaip tik prisijungsite. Galite tai padaryti vartotojo valdymo pulte.

Ačiū,
{2} Komanda';
$l['email_randompassword1'] = '{1},

Ačiū, kad užsiregistravote {2}. Žemiau yra Jūsų prisijungimo vardas ir sugeneruotas slaptažodis. Prisijungti prie {2}, Jums reikės šių duomenų.

El. pašto adresas
Slaptažodis: {4}

Rekomenduojame pasikeisti slaptažodį iškarto kaip tik prisijungsite. Galite tai padaryti vartotojo valdymo pulte.

Ačiū,
{2} Komanda';
$l['email_randompassword2'] = '{1},

Ačiū, kad užsiregistravote {2}. Žemiau yra Jūsų prisijungimo vardas ir sugeneruotas slaptažodis. Prisijungti prie {2}, Jums reikės šių duomenų.

Prisijungimo vardas: {3} (arba jūsų el. pašto adresas)
Slaptažodis: {4}

Rekomenduojame pasikeisti slaptažodį iškarto kaip tik prisijungsite. Galite tai padaryti vartotojo valdymo pulte.

Ačiū,
{2} Komanda';
$l['email_sendtofriend'] = 'Labas,

{1} nuo {2} manau, kad tau bus įdomu paskaityti šį tinklalapį:

{3}

{1} žinutė:
------------------------------------------
{4}
------------------------------------------

Ačiū,
{2} Komanda
';
$l['email_forumsubscription'] = '{1},

{2} ką tik parašė temoje, kurią jūs užsiprenumeravote puslapyje {3}. Temos pavadinimas: {4}.

Tai yra trumpa žinutės ištrauka:
------------------------------------------
{5}
------------------------------------------

Peržiūrėti šią temą galite spausdami šią nuorodą:
{6}/{7}

Temoje gali būtu ir daugiau vartotojų skelbtų žinučių, bet jūs negausite naujų pranešimų, kol neaplankysite forumo.

Ačiū,
{3} Komanda

------------------------------------------
Atsisakyti prenumeratos:

Jeigu jūs nenorite toliau gauti šių pranešimų, spauskite ant žemiau esančios nuorodos ir prenumerata bus atšaukta:
{6}/usercp2.php?action=removesubscription&tid={8}&my_post_key={9}

------------------------------------------';
$l['email_activateaccount'] = '{1},

Kad užbaigtumėte registracijos procesą {2}, paspauskite ant nuorodos esančios žemiau.

{3}/member.php?action=activate&uid={4}&code={5}

Jeigu aukščiau esanti nuoroda neveikia tinkamai, apsilankykite {3}/member.php?action=activate

Jums reikės įvesti šiuos duomenis:
Prisijungimo vardas: {1}
Aktyvavimo kodas: {5}

Ačiū,
{2} Komanda';
$l['email_activateaccount1'] = '{1},

Kad užbaigtumėte registracijos procesą {2}, paspauskite ant nuorodos esančios žemiau.

{3}/member.php?action=activate&uid={4}&code={5}

Jeigu aukščiau esanti nuoroda neveikia tinkamai, apsilankykite {3}/member.php?action=activate

Jums reikės įvesti šiuos duomenis:
El. pašto adresas
Aktyvavimo kodas: {5}

Ačiū,
{2} Komanda';
$l['email_activateaccount2'] = '{1},

Kad užbaigtumėte registracijos procesą {2},  paspauskite ant nuorodos esančios žemiau.

{3}/member.php?action=activate&uid={4}&code={5}

Jeigu aukščiau esanti nuoroda neveikia tinkamai, apsilankykite {3}/member.php?action=activate

Jums reikės įvesti šiuos duomenis:
Prisijungimo vardas: {1} (arba jūsų el. pašto adresas)
Aktyvavimo kodas: {5}

Ačiū,
{2} Komanda';
$l['email_subscription'] = '{1},

{2} ką tik parašė temoje, kurią jūs užsiprenumeravote puslapyje {3}. Temos pavadinimas: {4}.

Tai yra trumpa žinutės ištrauka:
------------------------------------------
{5}
------------------------------------------

Peržiūrėti šią temą galite spausdami šią nuorodą:
{6}/{7}

Temoje gali būtu ir daugiau vartotojų skelbtų žinučių, bet jūs negausite naujų pranešimų, kol neaplankysite forumo.

Ačiū,
{3} Komanda

------------------------------------------
Atsisakyti prenumeratos:

Jeigu jūs nenorite toliau gauti šių pranešimų, spauskite ant žemiau esančios nuorodos ir prenumerata bus atšaukta:
{6}/usercp2.php?action=removesubscription&tid={8}&my_post_key={9}

------------------------------------------';
$l['email_reachedpmquota'] = '{1},

Tai yra automatinis perspėjimas nuo {2} skirtas įspėti, kad pasiektas Privačių žinučių limitas.

Vienas ar daugiau vartotojų nesėkmingai Jums bandė siųsti asmenines žinutes, dėl šios priežasties.

Prašome ištrinti keletą privačių žinučių, taip pat siūlome ištinti jas ir iš šiukšliadėžės.

Ačiū,
{2} Komanda
{3}';
$l['email_changeemail'] = '{1},

Gavome prašymą {2} pakeisti Jūsų el. pašto adresą (žiūrėti detales žemiau).

Senas el. pašto adresas: {3}
Naujas el. pašto adresas: {4}

Jeigu šie pakeitimai yra teisingi, užbaikite tikrinimo procesą {2} spausdami žemiau esančią nuorodą.

{5}/member.php?action=activate&uid={8}&code={6}

Jeigu nuoroda neveikia teisingai, spauskite šią nuorodą {5}/member.php?action=activate

Jums reikės įvesti šiuos duomenis:
Prisijungimo vardas: {7}
Aktyvavimo kodas: {6}

Jeigu praleisite tikrinimo procesą, jūsų profilis nebus atnaujintas ir bus naudojamas dabartinis el. pašto adresas.

Ačiū,
{2} Komanda
{5}';
$l['email_changeemail_noactivation'] = '{1},
Gavome prašymą {2} pakeisti Jūsų el. pašto adresą (žiūrėti detales žemiau).

Senas el. pašto adresas: {3}
Naujas el. pašto adresas: {4}

Šis pakeitimas buvo įvykdytas automatiškai. Jeigu keitimą darėte ne Jūs, kreipkitės į Administratorių.

Ačiū,
{2} Komanda
{5}';
$l['email_changepassword'] = '{1},

Gavote šį laišką, nes Jūs arba kažkas turintis Jūsų slaptažodį katik jį pakeitė.

prisijungimo vardas: {1}
El. pašto adresas: {2}

Jeigu šlaptažodį pakeitėtė ne Jūs, susisiekite su Administratoriumi.

Ačiū,
{3} Komanda
{4}';
$l['email_newpm'] = '{1},

Jūs gavote naują privačią žinutę {3} nuo {2}:

------------------------------------------
{5}
------------------------------------------

Pežiūrėti, atsakyti ar persiųsti šią žinutę galite spausdami ant nuorodos žemiau:

{4}/private.php

Įsidėmekite, kad negausite naujų pranešimų el.paštu, apie naujas žinutes, kol neapsilankysite {3}.

Galite išjungti įspėjamuosius pranešimus savo profilio nustatymuose, paspaudę žemiau esančią nuorodą:

{4}/usercp.php?action=options

Ačiū,
{3} Komanda
{4}';
$l['email_emailuser'] = '{1},

{2} from {3} has sent you the following message:
------------------------------------------
{5}
------------------------------------------

Thank you,
{3} Staff
{4}

------------------------------------------
Don\'t want to receive email messages from other members?

If you don\'t want other members to be able to email you please visit your User Control Panel and enable the option \'Hide your email from other members\':
{4}/usercp.php?action=options

------------------------------------------';
$l['email_groupleader_joinrequest'] = '{1},

{2} has requested to join {3} on {4} (see below).

Reason: {5}

To accept or decline this request, go to

{6}/managegroup.php?gid={7}

Thank you,
{4} Staff';
$l['email_contact_subject'] = 'Kontaktas: {1}';
$l['email_contact'] = 'El, paštas: {1}
Forumo profilis: {2}
IP Addresas: {3}
Žinutė:
{4}';
$l['pmsubject_subscription'] = 'Nauja žinutė temoje {1}';
$l['pm_subscription'] = '{1},

{2} katik paliko atsakymą temoje, kurią Jūs prenumeruojate. Temos pavadinimas: {3}.

Tai yra trumpa ištrauka:
------------------------------------------
{4}
------------------------------------------

Norėdami pežiūrėti visą temą spauskite nuorodą žemiau:
[url]{5}/{6}[/url]

Temoje, kali būti ir daugiau naujų pranešimų, bet jūs negausite naujų pranešimų, kol neapsilankysite šioje temoje.

------------------------------------------
Prenumeratos informacija:

Jeigu nenorite gauti pranešimų apie komentarus šioje temoje, spauskite nuorodą žemiau:
[url]{5}/usercp2.php?action=removesubscription&tid={7}&my_post_key={8}[/url]

------------------------------------------';
$l['email_broken_task_subject'] = 'MyBB task error on {1}';
$l['email_broken_task'] = 'Your copy of MyBB running on {1} ({2}) has experienced an error with the task system.

The task file for {3} is missing.

This task has been disabled until issue is resolved.';
