<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 16:21:38 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Pagalbos dokumentai';
$l['nav_smilies'] = 'Emocijų sąrašas';
$l['nav_syndication'] = 'Naujausios Temos Sindikavimas (RSS)';
$l['aol_im'] = 'AOL IM';
$l['skype'] = 'Skype';
$l['yahoo_im'] = 'Yahoo IM';
$l['skype_center'] = 'Skype centras';
$l['chat_on_skype'] = 'Susiraįykite su {1} per Skype';
$l['call_on_skype'] = 'Skambinti {1} per Skype';
$l['yahoo_center'] = 'Yahoo! centras';
$l['send_y_message'] = 'Siųsti {1} Yahoo! žinutę.';
$l['view_y_profile'] = 'Žiūrėti {1} Yahoo! profilį.';
$l['aim_center'] = 'AOL IM centras';
$l['download_aim'] = 'Atsisiųsti AIM';
$l['aim_remote'] = 'AIM nuotolinis';
$l['send_me_instant'] = 'Siųsk man greitąją žinutę';
$l['add_me_buddy_list'] = 'Pridėk mane į savo draugų sąrašą';
$l['add_remote_to_page'] = 'Add Remote to Your Page';
$l['download_aol_im'] = 'Atsisiųsti AOL';
$l['buddy_list'] = 'Draugų sąrašas';
$l['online'] = 'Prisijungęs';
$l['online_none'] = '<em>Nėra prisijungusių draugų</em>';
$l['offline'] = 'Atsijungęs';
$l['offline_none'] = '<em>Nėra atsijungusių draugų</em>';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'Siųsti privačią žinutę';
$l['last_active'] = '<strong>Paskutinis aktyvus:</strong> {1}';
$l['close'] = 'Uždaryti';
$l['no_buddies'] = '<em>Draugų sąrašas tuščias.</em>';
$l['help_docs'] = 'Pagalbos dokumentai';
$l['search_help_documents'] = 'Ieškoti pagalbos dokumentuose';
$l['search_by_name'] = 'Ieškoti pagal vardą';
$l['search_by_document'] = 'Ieškoti pagal dokumentą';
$l['enter_keywords'] = 'Įveskite raktažodžius';
$l['search'] = 'Paieška';
$l['redirect_searchresults'] = 'Thank you, your search has been submitted and you will now be taken to the results list.';
$l['search_results'] = 'Search Results';
$l['help_doc_results'] = 'Help Document Results';
$l['document'] = 'Document';
$l['error_nosearchresults'] = 'Sorry, but no results were returned using the query information you provided. Please redefine your search terms and try again.';
$l['no_help_results'] = 'Sorry, but no results were returned using the query information you provided.';
$l['error_helpsearchdisabled'] = 'The ability to search the help documents has been disabled by the Administrator.';
$l['smilies_listing'] = 'Smilies Listing';
$l['name'] = 'Name';
$l['abbreviation'] = 'Abbreviation';
$l['click_to_add'] = 'Click a smilie to insert it into your message';
$l['close_window'] = 'close window';
$l['who_posted'] = 'Who Posted?';
$l['total_posts'] = 'Total Posts:';
$l['user'] = 'User';
$l['num_posts'] = '# Posts';
$l['forum_rules'] = '{1} - Rules';
$l['error_invalid_limit'] = 'The feed item limit you entered is invalid. Please specify a valid limit.';
$l['syndication'] = 'Latest Thread Syndication';
$l['syndication_generated_url'] = 'Your Generated Syndication URL:';
$l['syndication_note'] = 'Below you can generate links to specific RSS syndication feeds. Links can be generated for all forums, per forum, or for a specific number of forums. You will then be presented with a link which you can copy in to an RSS reader. <i><a href="http://en.wikipedia.org/wiki/RSS" target="_blank">What is RSS?</a></i>';
$l['syndication_forum'] = 'Forum to Syndicate:';
$l['syndication_forum_desc'] = 'Please select a forum from the right. Use the CTRL key to select multiple forums.';
$l['syndication_version'] = 'Feed Version:';
$l['syndication_version_desc'] = 'Please select the version of the feeds you wish to generate.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (Default)';
$l['syndication_generate'] = 'Generate Syndication URL';
$l['syndication_limit'] = 'Limit:';
$l['syndication_limit_desc'] = 'The amount of threads to download at one time. Not recommended to be beyond 50.';
$l['syndication_threads_time'] = 'threads at a time';
$l['syndicate_all_forums'] = 'Syndicate All Forums';
$l['redirect_markforumread'] = 'The selected forum has been marked as read.';
$l['redirect_markforumsread'] = 'All the forums have been marked as read.';
$l['redirect_forumpasscleared'] = 'The stored password for this forum has been cleared.';
$l['redirect_cookiescleared'] = 'All cookies have been cleared.';
$l['error_invalidforum'] = 'Invalid forum';
$l['error_invalidhelpdoc'] = 'The specified help document does not appear to exist.';
$l['error_invalidimtype'] = 'This user does not have this type of instant messenger account specified in their profile.';
$l['error_invalidsearch'] = 'An invalid search was specified.  Please go back and try again.';
$l['error_no_search_support'] = 'This database engine does not support searching.';
$l['error_searchflooding'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another {2} seconds before attempting to search again.';
$l['error_searchflooding_1'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another 1 second before attempting to search again.';
$l['dst_settings_updated'] = 'Your daylight saving time settings have automatically been adjusted.<br /><br />You will now be taken back to the forum index.';
