<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 19:34:31 +0000
// --------------------------------------------------------------------------------

$l['myalerts'] = 'Mano įspėjimai';
$l['myalerts_page_title'] = 'Naujausi įspėjimai';
$l['myalerts_page_getnew'] = 'Tikrinkite ar yra naujų įspėjimų';
$l['myalerts_alerts'] = 'Įspėjimai';
$l['myalerts_settings_page_title'] = 'Įspėjimų nustatymai';
$l['myalerts_online_location_listing'] = 'Įspėjimų žiūrėjimas';
$l['myalerts_unread_title'] = 'Neskaityti įspėjimai';
$l['myalerts_no_alerts'] = 'Nėra naujų įspėjimų';
$l['myalerts_rep'] = '{1} pakeitė tavo reputaciją.';
$l['myalerts_pm'] = '{1} atsiuntė tau privačią žinutę pavadinimu "{2}".';
$l['myalerts_buddylist'] = '{1} pridėjo tave į savo draugų sąrašą.';
$l['myalerts_quoted'] = '{1} pacitavo tave {2}.';
$l['myalerts_post_threadauthor'] = '{1} atsakė tavo temoje "{2}". Šioje temoje gali būti daugiau pranešimų';
$l['myalerts_subscribed_thread'] = '{1} atsakė tavo prenumeruojamoje temoje "{2}".';
$l['myalerts_setting_rep'] = 'Gauti įspėjimus dėl reputacijos pasikeitimų?';
$l['myalerts_setting_pm'] = 'Gauti įspėjimus dėl privačių žinučių?';
$l['myalerts_setting_buddylist'] = 'Gauti įspėjimus dėl pridėjimo į draugų sąrašą?';
$l['myalerts_setting_quoted'] = 'Gauti įspėjimus dėl citavimo pranešime?';
$l['myalerts_setting_post_threadauthor'] = 'Gaut įspėjimus dėl paminėjimo tavo temoje?';
$l['myalerts_setting_subscribed_thread'] = 'Gauti įspėjimus dėl atsakymų tavo prenumeruojamose temose?';
$l['myalerts_settings_save'] = 'Išsaugoti nustatymus';
$l['myalerts_settings_updated'] = 'Įspėjimų nustatymai sėkmingai atnaujinti. Siunčiam atgal į nustatymų puslapį.';
$l['myalerts_settings_updated_title'] = 'Įspėjimų nustatymai atnaujinti.';
$l['myalerts_delete_deleted'] = 'Įspėjimas sėkmingai ištrintas.';
$l['myalerts_delete_error'] = 'Įspėjimas šiuo metu negali būti ištrintas.';
$l['myalerts_delete_read_confirm'] = 'Ar tikrai ištrinti visus skaitytus įspėjimus? Nebus galima atstatyti!';
$l['myalerts_delete_all_confirm'] = 'Ar tikrai ištrinti visus įspėjimus? Nebus galima atstatyti!';
$l['myalerts_delete_mass_deleted'] = 'Įspėjimai ištrinti';
$l['myalerts_delete_all'] = 'Visi įspėjimai sėkmingai ištrinti.';
$l['myalerts_usercp_nav'] = 'Įspėjimai';
$l['myalerts_usercp_nav_alerts'] = 'Žiūrėti įspėjimus';
$l['myalerts_usercp_nav_settings'] = 'Įspėjimų nustatymai';
$l['myalerts_usercp_nav_delete_read'] = 'Trinti senus įspėjimus';
$l['myalerts_usercp_nav_delete_all'] = 'Trinti visus įspėjimus';
$l['myalerts_error_alert_not_found'] = 'Įspėjimas nerastas.';
$l['myalerts_delete'] = 'Trinti';
