<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 19:42:37 +0000
// --------------------------------------------------------------------------------

$l['myfbconnect'] = 'Mano Facebook Prisijungimas';
$l['myfbconnect_login'] = 'Prisijungti su Faccebook';
$l['myfbconnect_redirect_loggedin'] = 'Sėkmingai prisijungėte su Facebook';
$l['myfbconnect_redirect_registered'] = 'Sėkmingai užsiregistravote ir prisijungėte per Facebook';
$l['myfbconnect_redirect_title'] = 'Seviki, {1}!';
$l['myfbconnect_error_noconfigfound'] = '';
$l['myfbconnect_error_noauth'] = '';
$l['myfbconnect_error_report'] = '';
$l['myfbconnect_error_report_generated'] = '';
$l['myfbconnect_error_alreadyloggedin'] = 'Jūs esate prisijungęs prie šio forumo.';
$l['myfbconnect_error_verifiedonly'] = '';
$l['myfbconnect_error_noidprovided'] = '';
$l['myfbconnect_error_unknown'] = 'Įvyko klaida.';
$l['myfbconnect_page_title'] = 'Facebook integracija';
$l['myfbconnect_settings_title'] = 'Facebook integracija';
$l['myfbconnect_settings_save'] = 'Saugoti';
$l['myfbconnect_settings_unlink'] = 'Atsieti mano paskyrą';
$l['myfbconnect_settings_fbavatar'] = 'Avataras ir viršelis';
$l['myfbconnect_settings_fbsex'] = 'Lytis';
$l['myfbconnect_settings_fbbio'] = 'Bio';
$l['myfbconnect_settings_fbdetails'] = 'Vardas ir pavardė';
$l['myfbconnect_settings_fbbday'] = 'Gimimo diena';
$l['myfbconnect_settings_fblocation'] = 'Vieta';
$l['myfbconnect_link'] = 'Spauskite čia norėdami susieti paskyrą su savo "Facebook"';
$l['myfbconnect_settings_whattosync'] = '';
$l['myfbconnect_settings_linkaccount'] = '';
$l['myfbconnect_settings_connected'] = '';
$l['myfbconnect_register_title'] = 'Facebook registracija';
$l['myfbconnect_register_basicinfo'] = 'Pasirinkite pagrindinius infos ant jūsų teisė. Jie jau alsuoja Jūsų "Facebook" duomenų, tačiau, jei norite juos pakeisti esate laisvi daryti. Sąskaita bus susijęs su savo Facebook vieno karto, automatiškai ir nepriklausomai nuo jūsų pasirinkimus.';
$l['myfbconnect_register_whattosync'] = 'Pasirinkite kokia informacija turėtume importuoti iš jūsų "Facebook". Mes iš karto sinchronizuosime norimų duomenų priėmimo tikslią kopiją iš jūsų Facebook paskyros, priklausomai nuo jūsų pasirinkimo.';
$l['myfbconnect_register_username'] = 'Vartotojo vardas:';
$l['myfbconnect_register_email'] = 'El. paštas:';
$l['myfbconnect_success_linked'] = 'Jūsų paskyra šioje diskusijų lentoje buvo tiesiogiai susieta su jūsų "Facebook".';
$l['myfbconnect_success_settingsupdated'] = 'Jūsų "Facebook" integracijos susiję parametrai buvo atnaujinti teisingai.';
$l['myfbconnect_success_settingsupdated_title'] = 'Nustatymai atnaujinti';
$l['myfbconnect_success_accunlinked'] = 'Jūsų "Facebook" paskyra buvo atsieta sėkmingai nuo MyBB.';
$l['myfbconnect_success_accunlinked_title'] = 'Paskyra atsieta';
$l['myfbconnect_viewing_loggingin'] = '<a href="myfbconnect.php?action=fblogin">Prisijungimas per Facebook</a>';
$l['myfbconnect_viewing_registering'] = '<a href="myfbconnect.php?action=fbregister">Registracija per Facebook</a>';
$l['myfbconnect_male'] = 'Vyras';
$l['myfbconnect_female'] = 'Moteris';
