<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 16:25:24 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Rašyti atsakymą';
$l['post_reply_to'] = 'Rašyti atsakymą {1}';
$l['post_new_reply'] = 'Rašyti naują atsakymą';
$l['reply_to'] = 'Atsakyti temoje: {1}';
$l['post_subject'] = 'Pranešimo pavadinimas:';
$l['your_message'] = 'Tavo žinutė:';
$l['post_options'] = 'Pranešimo nustatymai:';
$l['options_sig'] = '<strong>Parašas:</strong> Įterpkite savo parašą. (tik registruoti)';
$l['options_emailnotify'] = '<strong>El. pašto pranešimai:</strong> gauti el. laišką kai tik atsiranda naujas pranešimas. (tik registruoti)';
$l['options_disablesmilies'] = '<strong>Išjungti šypsenėles:</strong> Nerodyti šypsenėlių šiame pranešime.';
$l['post_reply'] = 'Skelbti atsakymą';
$l['preview_post'] = 'Peržiūrėti atsakymą';
$l['mod_options'] = 'Moderatoriau nustatymai:';
$l['close_thread'] = '<strong>Uždaryti temą</strong>: neleisti toliau komentuoti šioje temoje.';
$l['stick_thread'] = '<strong>Prilipinti temą:</strong> prilipinti temą forumo viršuje.';
$l['forum_rules'] = '{1} - Taisyklės';
$l['thread_review'] = 'Temos peržiūra (Naujausi pirmiausiai)';
$l['thread_review_more'] = 'Ši temą turi daugiau negu {1} atsakymą. <a href="{2}">Skaitykite vią temą.</a>';
$l['posted_by'] = 'Įrašas nuo';
$l['draft_saved'] = 'Naują pranešimas sėkmingai išsaugotas kaip juodraštis.<br />Dabar jūs būsite nukreitpas į juodrašius.';
$l['error_post_already_submitted'] = 'Jūs jau paskelbėte šį pranešimą nurodytoje temoje. Prašome aplankyti temą, kad pamatytumėte savo atsakymą.';
$l['multiquote_external_one'] = 'Jūs pasirinkote vieną pranešimą, esantį už šios temos ribų.';
$l['multiquote_external'] = 'Jūs pasirinkote {1} pranešimus(-ų), esantčius už šios temos ribų.';
$l['multiquote_external_one_deselect'] = 'atžymėti šį pranešimą';
$l['multiquote_external_deselect'] = 'atžymėti šiuos pranešimus';
$l['multiquote_external_one_quote'] = 'Taip pat cituoti šį pranešimą ';
$l['multiquote_external_quote'] = 'Taip pat cituoti šiuos pranešimus';
$l['redirect_newreply'] = 'Ačiū, jūsų atsakymas paskelbtas.';
$l['redirect_newreply_moderation'] = 'Administratorius nurodė, kad visi nauji pranešimai turi buti moderuojami. Būsite perkeltas į temą.';
$l['redirect_newreply_post'] = '<br />Būsite nukreiptas į savo pranešimą.';
$l['redirect_newreplyerror'] = 'Atsiprašome, Jūsų atsakymas atmestas, dėl per trumpo turinio. <br />Būsite nukreiptas į temą.';
$l['redirect_threadclosed'] = 'Negalite skelbti pranešimų, nes tema yra uždaryta.';
$l['error_post_noperms'] = 'Neturite teisės redaguoti šį juodraštį.';
$l['error_stop_forum_spam_spammer'] = 'Sorry, your {1} matches that of a known spammer. If you feel this is a mistake, please contact an administrator';
$l['error_stop_forum_spam_fetching'] = 'Sorry, something went wrong verifying your reply against a spammer database. Most likely the database couldn\'t be accessed. Please try again later.';
$l['error_suspendedposting'] = 'Your posting privileges are currently suspended {1}.<br /><br />

Suspension Date: {2}';
$l['error_suspendedposting_temporal'] = 'until {1}';
$l['error_suspendedposting_permanent'] = 'permanently';
