<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 16:39:35 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Portalas';
$l['posted_by'] = 'Austorius:';
$l['forum'] = 'Forumas:';
$l['replies'] = 'Atsakymai';
$l['no_replies'] = 'Nėra atsakymų';
$l['latest_threads'] = 'Naujausios temos';
$l['latest_threads_replies'] = 'Atsakymai:';
$l['latest_threads_views'] = 'Peržiūros:';
$l['latest_threads_lastpost'] = 'Paskutinis pranešimas:';
$l['private_messages'] = 'Privačios žinutės';
$l['pms_received_new'] = '{1}, turite <b>{2}</b> neskaitytą(-as) žinutę(-es).';
$l['pms_unread'] = 'Neskaitytos žinutės';
$l['pms_total'] = 'Viso žinučių';
$l['search_forums'] = 'Ieškoti forumuose';
$l['advanced_search'] = 'Išplėstinė paieška';
$l['forum_stats'] = 'Forumo statistika';
$l['num_members'] = 'Vartotojai:';
$l['latest_member'] = 'Naujausias vartotojas:';
$l['num_threads'] = 'Forumo temos:';
$l['num_posts'] = 'Forumo pranešimai:';
$l['full_stats'] = 'Pilna statistika';
$l['welcome'] = 'Sveiki, {1}';
$l['guest'] = 'Svečias';
$l['guest_welcome_registration'] = 'Jūs turite <a href="{1}">užsiregistruoti</a> prieš skelbdami pranešimus forumuose.';
$l['username'] = 'Vartotojo vardas';
$l['password'] = 'Slaptažodis';
$l['login'] = 'Prisijungti!';
$l['member_welcome_lastvisit'] = 'Paskutinis apsilankymas:';
$l['since_then'] = 'Nuo tada, būta:';
$l['new_announcements'] = '{1} naujų skelbimų';
$l['new_announcement'] = '1 naujas skelbimas';
$l['new_threads'] = '{1} naujų temų';
$l['new_thread'] = '1 nauja tema';
$l['new_posts'] = '{1} naujų pranešimų';
$l['new_post'] = '1 naujas pranešimas';
$l['view_new'] = 'Žiūrėti naujus pranešimus';
$l['view_todays'] = 'Žiūrėti šiandienos pranešimus';
$l['online'] = 'Prisijungę vartotojai';
$l['online_user'] = 'Šiuo metu yra 1 prisijungęs vartotojas';
$l['online_users'] = 'Šiuo metu yra <b>{1}</b> prisijungusių vartotojų.';
$l['online_counts'] = '<b>{1}</b> Vartotojas(-ai) | <b>{2}</b> Svečias(-ai)';
$l['print_this_item'] = 'Spausdinti';
$l['send_to_friend'] = 'Siųsti draugui';
$l['latest_announcements'] = 'Naujausi skelbimai';
$l['portal_disabled'] = 'Protalo funkcija išjungta.';
