<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Mon, 18 Apr 2016 20:09:45 +0000
// --------------------------------------------------------------------------------

$l['forum'] = 'Forumas:';
$l['printable_version'] = 'Versija spausdinimui';
$l['pages'] = 'Puslapiai:';
$l['thread'] = 'Tema:';
