<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Mon, 25 Jul 2016 14:32:31 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'Privačios žinutės';
$l['nav_send'] = 'Kurti';
$l['nav_tracking'] = 'Žinutės sekimas';
$l['nav_folders'] = 'Aplankų valdymas';
$l['nav_empty'] = 'Tušti aplankai';
$l['nav_export'] = 'Eksportuoti žinutes';
$l['nav_search'] = 'Paieška';
$l['nav_results'] = 'Rezultatai';
$l['new_pm'] = 'Nauja žinutė';
$l['old_pm'] = 'Sena žinutė';
$l['reply_pm'] = 'Atsakė į';
$l['fwd_pm'] = 'Persiųsta žinutė';
$l['pms_disabled'] = 'Administratorius išjungė privačių žinučių funkciją.';
$l['private_messaging'] = 'Privačios žinutės';
$l['inbox'] = 'Pašto dėžutė';
$l['compose_message2'] = 'Kurti žinutę';
$l['manage_folders'] = 'Valdyti aplankus';
$l['pm_search_results'] = 'Privačių žinučių paieškos rezultatai';
$l['message_title'] = 'Žinutės pavadinimas';
$l['sender'] = 'Siuntėjas';
$l['sentto'] = 'Įšsiųsta į';
$l['date_sent'] = 'Siuntimo data/laikas';
$l['desc'] = 'maž.';
$l['asc'] = 'did.';
$l['delete_pm'] = 'Trinti';
$l['move_to'] = 'Iškelti į';
$l['or'] = 'arba';
$l['selected_messages'] = 'pažymėtos žinutės';
$l['go'] = 'Pirmyn!';
$l['pmspaceused'] = ' panaudota vietos AŽ.';
$l['jump_folder'] = 'Peršokti į aplanką:';
$l['archive_messages'] = 'Eksportuoti privačias žinutes';
$l['archive_note'] = 'Šis įrankis leis jums parsisiųsti savo privačias žinutes, pagal pasirinktą scenarijų';
$l['folders'] = 'Aplankai:';
$l['all_folders'] = 'Visi aplankai';
$l['date_limit'] = 'Datos limitas:';
$l['date_limit_older'] = 'Eksportuoti žinutes senesnes nei';
$l['date_limit_newer'] = 'Eksportuoti žinutes naujesnes nei';
$l['date_limit_disregard'] = 'Nepaisyti datos';
$l['date_limit_days'] = 'dienos';
$l['export_unread'] = 'Eksportuoti neskaitytas žinutes?';
$l['delete_archived'] = 'Trinti eksportuotas žinutes?';
$l['delete_archived_note'] = 'Ar norite, kad jūsų žinutės būtų ištrintos po to kai jas eksportuosite?';
$l['export_format'] = 'Eksportuojamo failo formatas:';
$l['export_format_note'] = 'Pasirinkite failo tipą, kuriuo norite gauti savo žinutes.';
$l['export_html'] = 'HTML failas (.html)';
$l['export_txt'] = 'Tekstinis failas (.txt)';
$l['export_csv'] = 'Importuojamas MS Excel failas (.csv)';
$l['private_messages_for'] = 'Privačios žinutės {1}';
$l['exported_date'] = 'Eksportuotos: {1}, {2}';
$l['subject'] = 'Tema:';
$l['to'] = 'Kam:';
$l['from'] = 'Nuo:';
$l['sent'] = 'Išsiųsta:';
$l['export_messages2'] = 'Atsisiųsti žinutes';
$l['empty_folders'] = 'Empty Private Messaging Folders';
$l['empty_folders2'] = 'Empty Folders';
$l['empty_note'] = 'Here you can delete private messages from selected folders at one time. Simply select the folders you wish the messages to be deleted from and click \'Delete\'. You cannot undo these changes.<br /><strong>Note: Once these messages are deleted there is no way to recover them.</strong>';
$l['num_messages'] = 'Message Count';
$l['empty_q'] = 'Empty Folder?';
$l['keep_unread'] = 'Keep Unread Messages';
$l['pm_folders'] = 'Private Messaging Folders';
$l['existing_folders'] = 'Existing Folders';
$l['edit_folder_note'] = 'You can change the names of your current private messaging folders here. To delete a folder, delete the name of the folder. Some folders cannot be removed.<br /><strong>Note: Deleting a folder will also delete any messages in it.</strong>';
$l['new_folders'] = 'Add New Folders';
$l['add_folders_note'] = 'Here you can create additional message folders. You do not have to fill in all of the text boxes.';
$l['update_folders'] = 'Update Folders';
$l['cannot_be_removed'] = 'Cannot be removed';
$l['reached_warning'] = 'Dėmesio. Pasiekėte žinučių limitą.';
$l['reached_warning2'] = 'To be able to receive messages you will need to delete old messages.';
$l['deny_receipt'] = '[Deny Receipt]';
$l['viewing_pm'] = 'Viewing PM:';
$l['reply'] = 'Atsakyti';
$l['reply_to_all'] = 'Atsakyti visiems';
$l['forward'] = 'Persiųsti';
$l['compose_pm'] = 'Kurti pirvačią žinutę';
$l['compose_to'] = 'Gavėjai:';
$l['compose_bcc'] = 'BCC:';
$l['compose_bcc_show'] = 'BCC';
$l['compose_bcc_show_title'] = 'Show the BCC input box allowing you to blind carbon copy messages to other users.';
$l['separate_names'] = 'Atskirkite vartotojų vardus kableliais.';
$l['max_recipients'] = '<br />Jūs galite siųsti žinutę daugiausiai <strong>{1}</strong> žmonėms.';
$l['compose_subject'] = 'Tema:';
$l['compose_message'] = 'Žinutė:';
$l['compose_options'] = 'Parinktys:';
$l['message_icon'] = 'Žinutės piktograma:';
$l['options_sig'] = '<strong>Parašas:</strong> įterpti parašą žinutėje.';
$l['options_disable_smilies'] = '<strong>Išjungti emocijas:</strong> išjungti emocijų rodymą žinutėje.';
$l['options_save_copy'] = '<strong>Saugoti kopiją:</strong> saugoti šios žinutės kopiją išsiųstų laiškų aplanke.';
$l['options_read_receipt'] = '<strong>Pranešti kada perskaito:</strong> gauti žinutę kai ši žinutė bus perskaityta.';
$l['send_message'] = 'Siųsti žinutę';
$l['save_draft'] = 'Saugoti kaip juodraštį';
$l['preview'] = 'Peržiūrėti';
$l['select_buddy'] = 'Arba pasirinkite draugą:';
$l['pm_tracking'] = 'Privačių žinučių sekimas';
$l['read_messages'] = 'Skaitytos žinutės';
$l['unread_messages'] = 'Neskaitytos žinutės';
$l['q'] = '?';
$l['dateread'] = 'Perskaitymo data';
$l['stop_tracking'] = 'Stabdyti sekmą';
$l['datesent'] = 'Išsiuntimo data';
$l['cancel'] = 'Atšaukti';
$l['export_date_sent'] = 'Data';
$l['export_folder'] = 'Aplankas';
$l['export_subject'] = 'Tema';
$l['export_to'] = 'Kam';
$l['export_from'] = 'Nuo';
$l['export_message'] = 'Žinutė';
$l['not_sent'] = 'N/A (neišsiųsta)';
$l['at'] = 'ties';
$l['nomessages'] = 'Šiame aplanke nėra privačių žinučių.';
$l['details'] = 'Detalės';
$l['message'] = 'Žinutė';
$l['buddy_list'] = 'Draugų sąrašas';
$l['multiple_recipients'] = '<em>Keli gavėjai</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Atsakyti į šią žinutę';
$l['forward_title'] = 'Persiųsti žinutę kitam vartotojui';
$l['delete_title'] = 'Ištrinti šią žinutę';
$l['you_replied_on'] = 'Atsakėte į šią žiutę {1}';
$l['you_forwarded_on'] = 'Persiuntėte šią žinutę {1}';
$l['you_replied'] = 'Atsakėte į šią žiutę {1}';
$l['you_forwarded'] = 'Persiuntėte šią žinutę {1}';
$l['select_from_buddies'] = 'Pasirinkti iš draugų';
$l['no_readmessages'] = 'Kolkas neturite sekamų žinučių.';
$l['no_unreadmessages'] = 'Kolkas neturite neperskaitytu sekamų žinučių.';
$l['stop_tracking_all'] = 'Stabdyti visų žinučių sekimą';
$l['enter_keywords'] = 'Įveskite raktažodžius';
$l['advanced_search'] = 'Išplėstinė paieška';
$l['search_pms'] = 'Ieškoti PŽ';
$l['advanced_private_message_search'] = 'Išplėtinė privačių žinučių paieška';
$l['search_criteria'] = 'Paieškos kriterijus';
$l['keywords'] = 'Raktažodžiai';
$l['search_in_subject'] = 'Ieškoti temoje';
$l['search_in_message'] = 'Ieškoti žinutėje';
$l['message_status'] = 'Žinutės būsena';
$l['message_status_new'] = 'Nauja';
$l['message_status_replied_to'] = 'Atsakė į';
$l['message_status_forwarded'] = 'Persiųsta';
$l['message_status_read'] = 'Perskaityta';
$l['folder'] = 'Aplankas';
$l['search_options'] = 'Paieškos nustaymai';
$l['sort_by'] = 'Rikiuoti pagal';
$l['sort_by_subject'] = 'Rikiuoti pagal: Temą';
$l['sort_by_sender'] = 'Rikiuoti pagal: Siuntėją';
$l['sort_by_date'] = 'Rikiuoti pagal: Datą';
$l['ascending_order'] = 'Didėjimo tvarka';
$l['descending_order'] = 'Mažėjimo tvarka';
$l['search_private_messages'] = 'Ieškoti privačiose žinutėse';
$l['check_all'] = 'Pažymėti visus';
$l['error_nopmsarchive'] = 'Sorry, but there are no private messages matching the criteria you specified.';
$l['error_invalidpmfoldername'] = 'Sorry, but a folder name you have entered contains characters which are not allowed.';
$l['error_emptypmfoldername'] = 'Sorry, but a folder name you have entered does not contain any text.  Please enter a name for the folder, or completely blank the name to delete the folder.';
$l['error_invalidpmrecipient'] = 'The recipient you entered is either invalid or doesn\'t exist. Please go back and enter a correct one.';
$l['error_invalidpm'] = 'Invalid PM';
$l['error_pmrecipientreachedquota'] = 'You cannot send a private message to {1} because he/she has reached their private messaging quota. They cannot be sent any message until their messages have been cleared out. An email has been sent to the user about this. Please try sending your message at a later stage.';
$l['error_recipientpmturnedoff'] = '{1} has chosen not to receive private messages or may not be allowed to do so. Therefore you may not send your private message to this user.';
$l['error_pmsturnedoff'] = 'You currently have private messages disabled in your profile.<br />To be able to use the private messaging system this setting must be enabled.';
$l['error_recipientignoring'] = 'We are sorry but we cannot process your private message to {1}. You do not have permission to perform this action.';
$l['error_pm_already_submitted'] = 'You have already submitted the same private message to the same recipient within the last 5 hours.';
$l['error_nopms'] = 'You must have one or more private messages in order to access this function.';
$l['error_minsearchlength'] = 'One or more of your search terms were shorter than the minimum length. The minimum search term length is {1} characters.<br /><br />If you\'re trying to search for an entire phrase, enclose it within double quotes. For example "The quick brown fox jumps over the lazy dog".';
$l['error_nosearchresults'] = 'Sorry, but no results were returned using the query information you provided. Please redefine your search terms and try again.';
$l['error_no_search_support'] = 'This database engine does not support searching.';
$l['error_nosearchterms'] = 'You did not enter any search terms. At a minimum, you must enter either some search terms or a username to search by.';
$l['error_searchflooding_1'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another 1 second before attempting to search again.';
$l['error_searchflooding'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another {2} seconds before attempting to search again.';
$l['error_invalidsearch'] = 'An invalid search was specified.  Please go back and try again.';
$l['redirect_pmsaved'] = 'The private message has been saved in your Drafts folder.';
$l['redirect_pmstrackingstopped'] = 'Tracking of the selected PMs has been stopped.';
$l['redirect_pmstrackingcanceled'] = 'The selected unread PMs have been deleted from the recipient\'s inbox.';
$l['redirect_allpmstrackingstopped'] = 'Tracking of all read PMs has been stopped.';
$l['redirect_pmsmoved'] = 'The selected private messages have been moved.';
$l['redirect_pmsdeleted'] = 'The selected private messages have been deleted.';
$l['redirect_pmsent'] = 'Thank you, your private message has successfully been sent.<br />You will now be returned to your private message inbox.';
$l['redirect_pmfoldersupdated'] = 'Thank you, your private messaging folders have successfully been updated.<br />You will now be returned to your private message Inbox.';
$l['redirect_pmfoldersemptied'] = 'The selected private messaging folders have successfully been emptied.<br />You will now be taken back to your Private Messaging Inbox.';
$l['redirect_searchresults'] = 'Thank you, your search has been submitted and you will now be taken to the results list.';
$l['quick_reply'] = 'Greitas atsakymas';
$l['message_note'] = 'Įveskite savo atsakymą į šią žinutę.';
$l['send_reply'] = 'Siųsti atsakymą';
$l['quickreply_signature'] = 'Parašas';
$l['quickreply_disable_smilies'] = 'Išjungti emocijas';
$l['quickreply_save_copy'] = 'Saugoti kopiją';
$l['quickreply_read_receipt'] = '<strong>Pranešti kada perskaito</strong>';
