<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Mon, 25 Jul 2016 14:04:23 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Ačiū, tema sėkmingai įvertinta. Būsite nukreiptas į temą.';
$l['error_invalidrating'] = 'Pasirinkote negalimą įvertinimą šiai temai. Grįžkite atgal ir bandykite iš naujo.';
$l['error_alreadyratedthread'] = 'Jūs jau esate įvertinęs šią temą.';
$l['error_cannotrateownthread'] = 'Negalite vertinti savo temos.';
$l['rating_votes_average'] = '{1} Balsas(-ai) - {2} iš 5  vidutiniškai';
$l['one_star'] = '1 žvaigždė iš 5';
$l['two_stars'] = '2 žvaigždės iš 5';
$l['three_stars'] = '3 žvaigždės iš 5';
$l['four_stars'] = '4 žvaigždės iš 5';
$l['five_stars'] = '5 žvaigždės iš 5';
$l['rating_added'] = 'Įvertinimas sėkmingai pridėtas!';
