<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : rootadmin
// Last edited date : Wed, 30 Mar 2016 08:46:53 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Siųsti temą draugui';
$l['send_thread'] = 'Siųsti draugui';
$l['recipient'] = 'Gavėjas:';
$l['recipient_note'] = 'Įvesk draugo el. paštą čia.';
$l['subject'] = 'Tema:';
$l['message'] = 'Žinutė:';
$l['error_nosubject'] = 'Privalai įvesti temą prieš siunčiant temą draugui';
$l['error_nomessage'] = 'Privalai įvesti žinutę prieš siunčiant temą draugui';
