<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : rootadmin
// Last edited date : Wed, 30 Mar 2016 08:44:29 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Ištrinti balsavimną';
$l['close_thread'] = 'Uždaryti temą';
$l['stick_thread'] = 'Prilipinti temą';
$l['author'] = 'Autorius';
$l['message'] = 'Žinutė';
$l['threaded'] = 'Teminis metodas';
$l['linear'] = 'Tiesioginis metodas';
$l['thread_modes'] = 'Temos metodas';
$l['next_oldest'] = 'Kitas senesnis';
$l['next_newest'] = 'Kitas naujesnis';
$l['view_printable'] = 'Žiūrė spausdinimo versiją';
$l['send_thread'] = 'Siųsti temą draugui';
$l['subscribe_thread'] = 'Prenumeruoti šią temą';
$l['unsubscribe_thread'] = 'Atsisakyti šios temo prenumeratos';
$l['add_poll_to_thread'] = 'Pridėti balsavimą šioje temoje';
$l['moderation_options'] = 'Moderavimo nustatymai:';
$l['delayed_moderation'] = 'Atidėtas moderavimui';
$l['thread_notes'] = 'Redaguoti / Žiūrėti temos užrašus';
$l['open_close_thread'] = 'Atidaryti / Uždaryti temą';
$l['approve_thread'] = 'Patvirtinti temą';
$l['unapprove_thread'] = 'Nepatvirtinti temos';
$l['soft_delete_thread'] = 'Panaikinti temą';
$l['restore_thread'] = 'Atstatyti temą';
$l['delete_thread'] = 'ištrinti temą';
$l['delete_posts'] = 'Ištrinti pasirinktus pranešimus';
$l['move_thread'] = 'Kelti / Kopijuoti temą';
$l['stick_unstick_thread'] = 'Prilipinti / Nulipinti temą';
$l['split_thread'] = 'Atskirti temą';
$l['merge_threads'] = 'Sujungti temas';
$l['remove_redirects'] = 'Panaikinti nukreipimus';
$l['remove_subscriptions'] = 'Panaikinti visas prenumeratas';
$l['poll'] = 'Balsavimas:';
$l['show_results'] = 'Rodyti rezultatus';
$l['edit_poll'] = 'Redaguoti balsavimą';
$l['public_note'] = '<b>Pastaba:</b> Tai yra viešas balsavimas, kiti vartotjai galės matyti už ką balsavai.';
$l['total'] = 'Viso';
$l['vote'] = 'Balsuoti!';
$l['total_votes'] = '{1} balsas(-ų)';
$l['you_voted'] = '* Tu pasirinkai šį atsakymą.';
$l['poll_closed'] = 'Balsavimas uždarytas.';
$l['poll_closes'] = 'Šis balsavimas pasibaigs: {1}';
$l['already_voted'] = 'Tu jau balsavai šioje apklausoje.';
$l['undo_vote'] = 'Panaikinti balsą';
$l['quick_reply'] = 'Greitas atsakymas';
$l['message_note'] = 'Rašykite savo atsakymą';
$l['signature'] = 'Parašas';
$l['email_notify'] = 'Email pranešimas';
$l['disable_smilies'] = 'Išjungti šypsenėles';
$l['post_reply'] = 'Skelbti atsakymą';
$l['post_reply_img'] = 'Skelbti atsakymą';
$l['new_reply'] = 'Naujas atsakymas';
$l['search_button'] = 'Paieška';
$l['post_thread'] = 'Skelbti temą';
$l['preview_post'] = 'Peržiūrėti pranešimą';
$l['rating_average'] = '{1} Balsas(-ų) - {2} Vidurkis';
$l['rate_thread'] = 'Įvertink temą:';
$l['thread_rating'] = 'Temos įvertinimas:';
$l['similar_threads'] = 'Tikriausiai panašios temos...';
$l['thread'] = 'Tema';
$l['replies'] = 'Atsakymai';
$l['views'] = 'Peržiūros';
$l['lastpost'] = 'Paskutinis pranešimas';
$l['messages_in_thread'] = 'Žinutes šioje temoje';
$l['users_browsing_thread'] = 'Vartotojų šioje temoje:';
$l['users_browsing_thread_guests'] = '{1} Svečias(-ių)';
$l['users_browsing_thread_invis'] = '{1} Nematomas(-ų) vartotojas(-ų)';
$l['users_browsing_thread_reading'] = 'Skaito...';
$l['inline_soft_delete_posts'] = 'Panaikinti pranešimus';
$l['inline_restore_posts'] = 'Atstatyti pranešimus';
$l['inline_delete_posts'] = 'Ištrinti pranešimus';
$l['inline_merge_posts'] = 'Sujungti pranešimus';
$l['inline_split_posts'] = 'Atskirti pranešimus';
$l['inline_move_posts'] = 'Kelti pranešimus';
$l['inline_approve_posts'] = 'Patvirtinti pranešimus';
$l['inline_unapprove_posts'] = 'Nepatvirtinti pranešimus';
$l['inline_post_moderation'] = 'Greitas pranešimų moderavimas:';
$l['inline_go'] = 'Eiti';
$l['clear'] = 'Išvalyti';
$l['thread_closed'] = 'Tema uždaryta';
$l['no_subject'] = 'Nėra temos';
$l['error_nonextnewest'] = 'Nėra naujesnių temų, negu paskutinė žiūrėta.';
$l['error_nonextoldest'] = 'Nėra senesnių temų, negu paskutinė žiūrėta.';
$l['quickreply_multiquote_selected'] = 'Cituoji vieną arba daugiau pranešimų.';
$l['quickreply_multiquote_now'] = 'Cituoti šiuos pranešimus';
$l['or'] = 'arba';
$l['quickreply_multiquote_deselect'] = 'panaikinti citatas';
$l['search_thread'] = 'Ieškoti temoje';
$l['enter_keywords'] = 'Įvesti raktažodžius';
$l['view_thread_notes'] = 'Temos pastabos';
$l['view_all_notes'] = 'Žiūrėti visas pastabas';
$l['save_changes'] = 'Išsaugoti pakeitimus';
$l['cancel_edit'] = 'Atšaukti redagavimą';
$l['quick_edit_update_error'] = 'Klaida redaguojant pranešimą:';
$l['quick_reply_post_error'] = 'Klaida skelbiant pranešimą:';
$l['quick_delete_error'] = 'Klaida trintant atsakymą:';
$l['quick_delete_success'] = 'Pranešimas sėkmingai ištrintas.';
$l['quick_delete_thread_success'] = 'Tema sėkmingai ištrinta.';
$l['quick_restore_error'] = 'Klaida atstatant pranešimą:';
$l['quick_restore_success'] = 'Pranešimas sėkmingai atstatytas.';
