<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 16:48:25 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Forumo statistika';
$l['stats_disabled'] = 'Negalite žiūrėti statistikos, ši funkcija išjungta.';
$l['board_stats'] = 'Forumo statistika';
$l['none'] = 'Nėra';
$l['totals'] = 'Viso';
$l['averages'] = 'Vidurkiai';
$l['posts'] = 'Pranešimai:';
$l['threads'] = 'Temos:';
$l['members'] = 'Vartotojai:';
$l['ppd'] = 'Pranešimų per dieną:';
$l['tpd'] = 'Temų per dieną:';
$l['mpd'] = 'Vartotojų per dieną:';
$l['ppm'] = 'Pranešimų vienam vartotojui:';
$l['tpm'] = 'Temų vienam vartotojui:';
$l['rpt'] = 'Atsakymų temoje:';
$l['no_posts'] = 'Ne';
$l['general'] = 'Bendrai';
$l['newest_member'] = 'Naujausias vartotojas:';
$l['members_posted'] = 'Vartotojai, kurie rašė pranešimus:';
$l['todays_top_poster'] = 'Šiandienos top pranešėjas: <b>{1}</b> (<b>{2}</b> pranešimų)';
$l['popular_forum'] = 'Populiariausias forumas: <b>{1}</b> (<b>{2}</b> pranešimų, <b>{3}</b> temų)';
$l['most_popular'] = 'Populiariausias...';
$l['most_replied_threads'] = 'Daugiausiai atsakymų temoje';
$l['most_viewed_threads'] = 'Labiausiai peržiūrėtos temos';
$l['not_enough_info_stats'] = 'Sorry, but there is not enough information on this board to generate statistics. Before statistics can be generated this board needs to contain at least 1 member and 1 thread.';
$l['replies'] = 'atsakymų';
$l['views'] = 'peržiūrų';
$l['top_referrer'] = 'Top refereris: <strong>{1}</strong> (<strong>{2}</strong> referalų)';
