<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 19:00:52 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'Visi forumai';
$l['forum'] = 'Forumas:';
$l['posted_by'] = 'Autorius:';
$l['on'] = 'on';
$l['portal'] = 'Portalas';
