<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Sat, 23 Jul 2016 15:56:48 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'Meniu';
$l['ucp_nav_messenger'] = 'Žinutės';
$l['ucp_nav_compose'] = 'Kurti';
$l['ucp_nav_tracking'] = 'Sekimas';
$l['ucp_nav_edit_folders'] = 'Redaguoti aplankus';
$l['ucp_nav_profile'] = 'Jūsų profilis';
$l['ucp_nav_edit_profile'] = 'Redaguoti profilį';
$l['ucp_nav_edit_options'] = 'Keisti nustatymus';
$l['ucp_nav_change_email'] = 'Keisti el. pašto adresą';
$l['ucp_nav_change_pass'] = 'Keisti slaptažodį';
$l['ucp_nav_change_username'] = 'Keisti vartotojo vardą';
$l['ucp_nav_edit_sig'] = 'Keisti parašą';
$l['ucp_nav_change_avatar'] = 'Keisti avatarą';
$l['ucp_nav_misc'] = 'Įvairūs';
$l['ucp_nav_editlists'] = 'Draugų/Ignoruojamų sąrašas';
$l['ucp_nav_favorite_threads'] = 'Mėgstamiausios temos';
$l['ucp_nav_subscribed_threads'] = 'Prenumeruojamos temos';
$l['ucp_nav_forum_subscriptions'] = 'Forumų prenumeratos';
$l['ucp_nav_drafts'] = 'Išsaugoti juodraščiai';
$l['ucp_nav_drafts_active'] = '<strong>Išsaugotų juodraščių ({1})</strong>';
$l['ucp_nav_notepad'] = 'Asmeniniai užrašai';
$l['ucp_nav_view_profile'] = 'Žiūrėti profilį';
$l['ucp_nav_home'] = 'UCP Pradžia';
$l['ucp_nav_usergroups'] = 'Narystė grupėje';
$l['ucp_nav_attachments'] = 'Tvarkyti priedus';
