<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Tue, 17 May 2016 08:23:51 +0000
// --------------------------------------------------------------------------------

$l['xstyled_aboutus'] = 'Apie mus';
$l['xstyled_aboutfirst'] = 'Fill me with text pleaaaaaaaaaaaaaaase.';
$l['xstyled_aboutsecond'] = 'Fill me with text pleaaaaaaaaaaaaaaase.';
$l['xstyled_aboutthird'] = 'Fill me with text pleaaaaaaaaaaaaaaase.';
$l['xstyled_aboutfourth'] = 'Fill me with text pleaaaaaaaaaaaaaaase.';
$l['xstyled_aboutfifth'] = 'Fill me with text pleaaaaaaaaaaaaaaase.';
$l['xstyled_navigation'] = 'Navigacija';
$l['xstyled_index'] = 'Indeksinis';
$l['xstyled_search'] = 'Paieška';
$l['xstyled_members'] = 'Vartotojai';
$l['xstyled_calendar'] = 'Kalendorius';
$l['xstyled_help'] = 'Pagalba';
$l['xstyled_quicklinks'] = 'Greitos nuorodos';
$l['xstyled_threads'] = 'Temos';
$l['xstyled_posts'] = 'Pranešimai';
$l['xstyled_moderators'] = 'Moderatoriai:';
$l['xstyled_newthread'] = 'Nauja tema';
$l['xstyled_startedby'] = 'Pradėta:';
$l['xstyled_replies'] = 'Atsakymai';
$l['xstyled_views'] = 'Peržiūros';
$l['xstyled_golastpost'] = 'Eiti į paskutinį pranešimą';
$l['xstyled_userbrowsing'] = 'Naršo:';
$l['xstyled_logo'] = 'Square';
$l['xstyled_loginat'] = 'Prisijungė';
$l['xstyled_loginfirstphrase'] = 'Square is a minimalistic template, renewed to 1.8 MyBB series. You can find a lot of details in the design, and of course, all squared.';
$l['xstyled_loginsecondphrase'] = 'Enjoy the crossbrowser design, tested in the latest Google Chrome, Mozilla Firefox and Opera versions.';
$l['xstyled_loginthirdphrase'] = '¡¿What are you waiting for?! Join us now!';
$l['xstyled_welcomephrase'] = 'Sveiki,';
$l['xstyled_usercp'] = 'Vartotojo CP';
$l['xstyled_friendlist'] = 'Žiūrėti draugų sąrašą';
$l['xstyled_changeavatar'] = 'Keisti avatarą';
$l['xstyled_changesignature'] = 'Keisti parašą';
$l['xstyled_pms'] = 'Privačios žinutės';
$l['xstyled_logout'] = 'Atsijungti';
$l['xstyled_admincp'] = 'Administratoriaus CP';
$l['xstyled_modcp'] = 'Moderatoriaus CP';
$l['xstyled_latestactivity'] = 'Paskutiniai veiksmai';
$l['xstyled_usersonline'] = 'Prisijungę vartotojų:';
$l['xstyled_hidesidebar'] = 'Slėpti šoninį meniu';
$l['xstyled_showsidebar'] = 'Rodyti šoninį meniu';
$l['xstyled_deletepm'] = 'Ištrinti PM';
$l['xstyled_edit'] = 'Redaguoti';
$l['xstyled_forwardpm'] = 'Persiųsti PM';
$l['xstyled_multiquote'] = 'Multi citata';
$l['xstyled_purgespammer'] = 'Naikinti spamerį';
$l['xstyled_delete'] = 'Ištrinti';
$l['xstyled_restore'] = 'Atstatyti';
$l['xstyled_reply'] = 'Atsakyti';
$l['xstyled_replypm'] = 'Atsakyti PM';
$l['xstyled_replyallpm'] = 'Atsakyti visiems PM';
$l['xstyled_report'] = 'Pranešti';
$l['xstyled_warn'] = 'Įspėti';
$l['xstyled_newreply'] = 'Naujas atsakymas';
$l['xstyled_threadclosed'] = 'Tema uždaryta';
$l['xstyled_createdby'] = 'Sukurė:';
