<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Mon, 25 Jul 2016 13:12:57 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = 'Profilis {1}';
$l['nav_warning_log'] = 'Įspėjimų registras';
$l['nav_add_warning'] = 'Įspėti vartotoją';
$l['nav_view_warning'] = 'Įspėjimo detalės';
$l['warning_for_post'] = '.. Pranešimas:';
$l['already_expired'] = 'Baigiasi';
$l['details_username'] = 'Vartotojo vardas';
$l['warning_active'] = 'Aktyvus';
$l['warning_revoked'] = 'Atšaukti';
$l['warning_log'] = 'Įspėjimų registras';
$l['warning'] = 'Įspėjimas';
$l['issued_by'] = 'Išsprendė';
$l['date_issued'] = 'Išsprendimo data';
$l['expiry_date'] = 'Baigiasi';
$l['active_warnings'] = 'Aktyvūs įspėjimai';
$l['expired_warnings'] = 'Pasibaigę įspėjimai';
$l['warning_points'] = '({1} taškai)';
$l['no_warnings'] = 'Šis vartotojas nėra gavęs įspėjimų arba visi buvo panaikinti.';
$l['warn_user'] = 'Įspėti vartotoją';
$l['post'] = 'Pranešimas:';
$l['warning_note'] = 'Administratorių užrašai:';
$l['details_warning_note'] = 'Administratorių užrašai';
$l['warning_type'] = 'Įspėjimo tipas:';
$l['custom'] = 'Pasirinktinė priežastis';
$l['reason'] = 'Priežastis:';
$l['points'] = 'Taškai:';
$l['details_reason'] = 'Priežastis';
$l['warn_user_desc'] = 'Here you can increase the warning level of this user if they\'ve violated one or more rules.';
$l['send_pm'] = 'Notify User:';
$l['send_user_warning_pm'] = 'Send this user a private message notifying them of this warning.';
$l['send_pm_subject'] = 'Subject:';
$l['warning_pm_subject'] = 'You have received a warning.';
$l['send_pm_message'] = 'Message:';
$l['warning_pm_message'] = 'Dear {1}

You have received a warning from the staff of {2}.
--

--';
$l['send_pm_options'] = 'Options:';
$l['send_pm_options_anonymous'] = '<strong>Anonymous PM</strong>: send this private message as an anonymous user.';
$l['expiration_never'] = 'permanently';
$l['expiration_hours'] = 'hours';
$l['expiration_days'] = 'days';
$l['expiration_weeks'] = 'weeks';
$l['expiration_months'] = 'months';
$l['redirect_warned_banned'] = '<br /><br />The user has also been moved to the {1} group {2}.';
$l['redirect_warned_suspended'] = '<br /><br />This users posting privileges have been suspended {1}.';
$l['redirect_warned_moderate'] = '<br /><br />All posts by this user will now be moderated {1}.';
$l['redirect_warned_pmerror'] = '<br /><br />Please note that the PM was not sent.';
$l['redirect_warned'] = 'The warning level of {1} has been increased to {2}%.{3}<br /><br />You will now be taken back to where you came from.';
$l['error_warning_system_disabled'] = 'You cannot use the warning system as it has been disabled by the board administrator.';
$l['error_cant_warn_group'] = 'You do not have permission to warn users of this group.';
$l['error_invalid_user'] = 'Selected user doesn\'t exist.';
$l['details'] = 'Details';
$l['view'] = 'View';
$l['current_warning_level'] = 'Current warning level: <strong>{1}%</strong> ({2}/{3})';
$l['warning_details'] = 'Warning Details';
$l['revoke_warning'] = 'Revoke this Warning';
$l['revoke_warning_desc'] = 'To revoke this warning please enter a reason below. This will not remove any bans or suspensions imposed by this warning.';
$l['warning_is_revoked'] = 'This Warning has been revoked';
$l['revoked_by'] = 'Revoked By';
$l['date_revoked'] = 'Date Revoked';
$l['warning_already_revoked'] = 'This warning has already been revoked.';
$l['no_revoke_reason'] = 'You did not enter a reason as to why you want to revoke this warning.';
$l['redirect_warning_revoked'] = 'This warning has successfully been revoked and the users warning points decreased.<br /><br />You will now be taken back to the warning.';
$l['result'] = 'Result:';
$l['result_banned'] = 'User will be moved to banned group ({1}) {2}';
$l['result_suspended'] = 'Posting privileges will be suspended {1}';
$l['result_moderated'] = 'Posts will be moderated {1}';
$l['result_period'] = 'for {1} {2}';
$l['result_period_perm'] = 'permanently';
$l['hour_or_hours'] = 'Hour(s)';
$l['day_or_days'] = 'Day(s)';
$l['week_or_weeks'] = 'Week(s)';
$l['month_or_months'] = 'Month(s)';
$l['expires'] = 'Expires:';
$l['new_warning_level'] = 'New warning level:';
$l['error_cant_warn_user'] = 'You do not have permission to warn this user.';
$l['existing_post_warnings'] = 'Existing Warnings for this Post';
