<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : rootadmin
// Last edited date : Wed, 30 Mar 2016 08:13:01 +0000
// --------------------------------------------------------------------------------

$l['xem_fast_rep_like_it'] = 'Patinka';
$l['xem_fast_rep_unlike_it'] = 'Nepatinka';
$l['xem_fast_rep_who_like_it'] = 'Vartotojai kuriems patinka';
$l['you'] = 'Tau';
$l['you_like_it'] = 'Tau patinko';
$l['like_it'] = 'patinka';
$l['and'] = 'ir';
$l['others_person_like_it'] = 'kitiems patinka';
