<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Lietuvių
// Author of the language pack : Marius Gentvilas
// Language pack translators website : http://www.f1news.lt
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : f1news.lt
// Last edited date : Mon, 18 Apr 2016 20:09:10 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'Jūs neįvedėte naujos temos.';
$l['post_moderation'] = 'Tavo pranešimas dabar yra moderuojamas.';
$l['thread_moderation'] = 'Tavo tema dabar yra moderuojama.';
$l['post_doesnt_exist'] = 'Pasirinktas pranešimas neegzistuoja.';
$l['thread_doesnt_exist'] = 'Pasirinkta temą neegzistuoja.';
$l['thread_closed_edit_subjects'] = 'Tema uždaryta ir jums nebus leista redaguoti pavadinimų.';
$l['no_permission_edit_subject'] = 'Neturite privilegijos redaguoti šios temos pavadinimo.';
$l['thread_closed_edit_message'] = 'Ši temą uždaryta ir greičiausiai negalėsite redaguoti žinučių.';
$l['no_permission_edit_post'] = 'Neturi leidimo redaguoti šią žinutę.';
$l['edit_time_limit'] = 'Žinutes galimą redaguoti tik {1} minutę po paskelbimo.';
$l['postbit_edited'] = 'Šis įrašą paskutinį kartą modifikavo: {1}';
$l['postbit_editreason'] = 'Redagavimo priežastis';
$l['save_changes'] = 'Išsaugoti pakeitimus';
$l['cancel_edit'] = 'Atšaukti redegavimą';
$l['answer_valid_not_exists'] = 'Klausimas, kurį bandote atsakyti neegzistuoja.';
$l['captcha_not_exists'] = 'Paveiklėlio kodas, kurį bandote perkrauti yra neegzistuojantis.';
$l['captcha_valid_not_exists'] = 'Paveiklėlio kodas, kurį bandote įvesti yra neegzistuojantis.';
$l['captcha_does_not_match'] = 'Paveiklėlio kodas, kurį įvedėte yra neteisingas. Įveskite kodą, būtent tokį koks parodytas paveikslėlyje.';
$l['captcha_matches'] = 'Paveiklėlio kodas, kurį įvedėte yra teisingas.';
$l['answer_does_not_match'] = 'Atsakymas, kurį įvedėte yra neteisingas.';
$l['banned_username'] = 'Jūsų įvertas prisijungimo vardas uždraustas naudoti';
$l['banned_characters_username'] = 'Jūsų slaptažodis turi vieną ar daugiau negalimų simbolių';
$l['complex_password_fails'] = 'Slaptažodis turi turėti didžąją raidę, mažąją raidę ir skaičių';
$l['username_taken'] = '{1} jau yra užregistruotas kito vartotojo';
$l['username_available'] = '{1} yra galimas';
$l['invalid_username'] = '{1} nėra registruoto vartotojo prisijungimo vardas';
$l['valid_username'] = '{1} yra teisingas nukreipėjas.';
$l['buddylist_error'] = 'Atrodo, jog neturite draugų savo draugų sąraše. Prašome pridėti draugus į sąrašą prieš bandant naudoti tai.';
$l['close'] = 'Uždaryti';
$l['select_buddies'] = 'Pasirinkti draugus';
$l['select_buddies_desc'] = 'Norint pridėti vieną ar kelis draugus kaip gavėjus, pasirinkite juos žemiau ir spauskite OK.';
$l['selected_recipients'] = 'Pasirinkti gavėjai';
$l['ok'] = 'OK';
$l['cancel'] = 'Atšaukti';
$l['online'] = 'Prisijungęs';
$l['offline'] = 'Atsijungęs';
$l['edited_post'] = 'Redaguotas pranešimas';
$l['usergroup'] = 'Vartotojų grupė';
